/* eslint-disable @typescript-eslint/no-throw-literal */
/* eslint-disable func-names */
import type { LocalityMappingData } from '../../models/mapping-data.model'

export default <LocalityMappingData>{
  AB: {
    'Avramesti (Arieseni)': 'Avramesti',
    'Avramesti (Avram Iancu)': 'Avramesti',
    'Barlesti (Bistra)': 'Barlesti',
    'Barlesti (Mogos)': 'Barlesti',
    'Barlesti (Scarisoara)': 'Barlesti',
    'Bobaresti (Sohodol)': 'Bobaresti',
    'Bobaresti (Vidra)': 'Bobaresti',
    'Bogdanesti (Mogos)': 'Bogdanesti',
    'Bogdanesti (Vidra)': 'Bogdanesti',
    'Botesti (Campeni)': 'Botesti',
    'Botesti (Scarisoara)': 'Botesti',
    'Botesti (Zlatna)': 'Botesti',
    'Butesti (Horea)': 'Butesti',
    'Butesti (Mogos)': 'Butesti',
    'Carpinis (Garbova)': 'Carpinis',
    'Carpinis (Rosia Montana)': 'Carpinis',
    'Costesti (Albac)': 'Costesti',
    'Costesti (Poiana Vadului)': 'Costesti',
    'Dealu Frumos (Garda de Sus)': 'Dealu Frumos',
    'Dealu Frumos (Vadu Motilor)': 'Dealu Frumos',
    'Dumbrava (Ciugud)': 'Dumbrava',
    'Dumbrava (Sasciori)': 'Dumbrava',
    'Dumbrava (Unirea)': 'Dumbrava',
    'Dumbrava (Zlatna)': 'Dumbrava',
    'Dupa Deal (Lupsa)': 'Dupa Deal',
    'Dupa Deal (Ponor)': 'Dupa Deal',
    Falaud() {
      throw 'Unavailable destination'
    },
    'Floresti (Bucium)': 'Floresti',
    'Floresti (Campeni)': 'Floresti',
    'Floresti (Ramet)': 'Floresti',
    'Floresti (Scarisoara)': 'Floresti',
    'Furduiesti (Campeni)': 'Furduiesti',
    'Furduiesti (Sohodol)': 'Furduiesti',
    'Hanasesti (Garda de Sus)': 'Hanasesti',
    'Hanasesti (Poiana Vadului)': 'Hanasesti',
    'Hoanca (Sohodol)': 'Hoanca',
    'Hoanca (Vidra)': 'Hoanca',
    'Incesti (Avram Iancu)': 'Incesti',
    'Incesti (Posaga)': 'Incesti',
    'Izvoarele (Blaj)': 'Izvoarele',
    'Izvoarele (Garda de Sus)': 'Izvoarele',
    'Izvoarele (Livezile)': 'Izvoarele',
    'Laz (Sasciori)': 'Laz',
    'Laz (Vintu de Jos)': 'Laz',
    'Lazesti (Scarisoara)': 'Lazesti',
    'Lazesti (Vadu Motilor)': 'Lazesti',
    'Lazuri (Lupsa)': 'Lazuri',
    'Lazuri (Sohodol)': 'Lazuri',
    Limba() {
      throw 'Unavailable destination'
    },
    'Lunca (Lupsa)': 'Lunca',
    'Lunca (Posaga)': 'Lunca',
    'Lunca (Valea Lunga)': 'Lunca',
    'Lunca (Vidra)': 'Lunca',
    'Lunca Larga (Bistra)': 'Lunca Larga',
    'Lunca Larga (Ocolis)': 'Lunca Larga',
    'Magura (Bucium)': 'Magura',
    'Magura (Galda de Jos)': 'Magura',
    'Matisesti (Ciuruleasa)': 'Matisesti',
    'Matisesti (Horea)': 'Matisesti',
    'Modolesti (Intregalde)': 'Modolesti',
    'Modolesti (Vidra)': 'Modolesti',
    'Moraresti (Ciuruleasa)': 'Moraresti',
    'Moraresti (Sohodol)': 'Moraresti',
    Piclisa() {
      throw 'Unavailable destination'
    },
    'Plai (Avram Iancu)': 'Plai',
    'Plai (Garda de Sus)': 'Plai',
    'Poiana (Bistra)': 'Poiana',
    'Poiana (Bucium)': 'Poiana',
    'Poiana (Sohodol)': 'Poiana',
    'Poieni (Blandiana)': 'Poieni',
    'Poieni (Bucium)': 'Poieni',
    'Poieni (Vidra)': 'Poieni',
    'Poienita (Arieseni)': 'Poienita',
    'Poienita (Vintu de Jos)': 'Poienita',
    Rametea() {
      throw 'Unavailable destination'
    },
    'Runc (Ocolis)': 'Runc',
    'Runc (Scarisoara)': 'Runc',
    'Runc (Vidra)': 'Runc',
    'Runc (Zlatna)': 'Runc',
    Saciori() {
      throw 'Unavailable destination'
    },
    'Sohodol (Albac)': 'Sohodol',
    'Trifesti (Horea)': 'Trifesti',
    'Trifesti (Lupsa)': 'Trifesti',
    'Valea Mare (Gurahont)': function () {
      throw 'Unavailable destination'
    },
    'Valea Poienii (Bucium)': 'Valea Poienii',
    'Valea Poienii (Ramet)': 'Valea Poienii',
    'Valea Sesii (Bucium)': 'Valea Sesii',
    'Valea Sesii (Lupsa)': 'Valea Sesii',
    'Valeni (Bucium)': 'Valeni',
    'Valeni (Metes)': 'Valeni',
    'Valtori (Vadu Motilor)': 'Valtori',
    'Valtori (Zlatna)': 'Valtori',
  },
  AR: {
    'Avram Iancu (Cermei)': 'Avram Iancu',
    'Avram Iancu (Varfurile)': 'Avram Iancu',
    'Valea Mare (Gurahont)': 'Valea Mare',
    'Valea Mare (Savarsin)': 'Valea Mare',
  },
  AG: {
    'Alunisu (Baiculesti)': 'Alunisu',
    'Alunisu (Bradulet)': 'Alunisu',
    'Badesti (Barla)': 'Badesti',
    'Badesti (Pietrosani)': 'Badesti',
    'Balilesti (Tigveni)': 'Balilesti',
    'Bratia (Berevoesti)': 'Bratia',
    'Bratia (Ciomagesti)': 'Bratia',
    'Brosteni (Aninoasa)': 'Brosteni',
    'Brosteni (Costesti)': 'Brosteni',
    'Bunesti (Cotmeana)': 'Bunesti',
    'Bunesti (Malureni)': 'Bunesti',
    'Capu Piscului (Godeni)': 'Capu Piscului',
    'Capu Piscului (Merisani)': 'Capu Piscului',
    'Cepari (Poiana Lacului)': 'Cepari',
    'Chiritesti (Suseni)': 'Chiritesti',
    'Chiritesti (Uda)': 'Chiritesti',
    'Chiritesti (Vedea)': 'Chiritesti',
    'Costesti (Cotmeana)': 'Costesti',
    'Cotmeana (Stolnici)': 'Cotmeana',
    'Cotu (Cuca)': 'Cotu',
    'Cotu (Uda)': 'Cotu',
    'Dealu Viilor (Mosoaia)': 'Dealu Viilor',
    'Dealu Viilor (Poiana Lacului)': 'Dealu Viilor',
    'Galasesti (Budeasa)': 'Galasesti',
    'Galasesti (Suseni)': 'Galasesti',
    'Glodu (Calinesti)': 'Glodu',
    'Glodu (Leordeni)': 'Glodu',
    'Golesti (Balilesti)': 'Golesti',
    'Golesti (Stefanesti)': 'Golesti',
    'Gruiu (Cateasca)': 'Gruiu',
    'Gruiu (Nucsoara)': 'Gruiu',
    'Lazaresti (Mosoaia)': 'Lazaresti',
    'Lazaresti (Schitu Golesti)': 'Lazaresti',
    'Malu (Barla)': 'Malu',
    'Malu (Godeni)': 'Malu',
    'Mioarele (Cicanesti)': 'Mioarele',
    'Pauleasca (Malureni)': 'Pauleasca',
    'Pauleasca (Micesti)': 'Pauleasca',
    'Piatra (Bradulet)': 'Piatra',
    'Piatra (Ciofrangeni)': 'Piatra',
    'Piatra (Stoenesti)': 'Piatra',
    'Poienari (Corbeni)': 'Poienari',
    'Poienari (Poienarii de Arges)': 'Poienari',
    'Poienari (Poienarii de Muscel)': 'Poienari',
    'Popesti (Cocu)': 'Popesti',
    'Popesti (Sapata)': 'Popesti',
    'Purcareni (Micesti)': 'Purcareni',
    'Purcareni (Popesti)': 'Purcareni',
    'Recea (Cateasca)': 'Recea',
    'Rudeni (Mihaesti)': 'Rudeni',
    'Rudeni (Suici)': 'Rudeni',
    'Serbanesti (Poienarii de Muscel)': 'Serbanesti',
    'Serbanesti (Rociu)': 'Serbanesti',
    'Slobozia (Popesti)': 'Slobozia',
    'Slobozia (Stoenesti)': 'Slobozia',
    'Stefanesti (Suseni)': 'Stefanesti',
    'Strambeni (Caldararu)': 'Strambeni',
    'Strambeni (Suseni)': 'Strambeni',
    'Suseni (Bogati)': 'Suseni',
    'Tigveni (Ratesti)': 'Tigveni',
    'Ungureni (Bradulet)': 'Ungureni',
    'Ungureni (Valea Iasului)': 'Ungureni',
    'Valea Popii (Mihaesti)': 'Valea Popii',
    'Valea Popii (Priboieni)': 'Valea Popii',
    'Vladesti (Tigveni)': 'Vladesti',
    'Zamfiresti (Cepari)': 'Zamfiresti',
    'Zamfiresti (Cotmeana)': 'Zamfiresti',
  },
  BC: {
    'Balanesti (Dealu Morii)': 'Balanesti',
    'Balanesti (Podu Turcului)': 'Balanesti',
    'Bogdanesti (Scorteni)': 'Bogdanesti',
    'Bogdanesti (Traian)': 'Bogdanesti',
    'Brad (Beresti-Bistrita)': 'Brad',
    'Brad (Filipeni)': 'Brad',
    'Brad (Negri)': 'Brad',
    'Buda (Berzunti)': 'Buda',
    'Buda (Blagesti)': 'Buda',
    'Buda (Rachitoasa)': 'Buda',
    'Cucuieti (Dofteana)': 'Cucuieti',
    'Cucuieti (Solont)': 'Cucuieti',
    'Dorneni (Plopana)': 'Dorneni',
    'Dorneni (Vultureni)': 'Dorneni',
    'Dragesti (Damienesti)': 'Dragesti',
    'Dragesti (Tatarasti)': 'Dragesti',
    'Dumbrava (Gura Vaii)': 'Dumbrava',
    'Dumbrava (Itesti)': 'Dumbrava',
    'Dumbrava (Rachitoasa)': 'Dumbrava',
    'Fantanele (Hemeius)': 'Fantanele',
    'Fantanele (Motoseni)': 'Fantanele',
    'Filipesti (Bogdanesti)': 'Filipesti',
    'Floresti (Caiuti)': 'Floresti',
    'Floresti (Huruiesti)': 'Floresti',
    'Floresti (Scorteni)': 'Floresti',
    'Galbeni (Filipesti)': 'Galbeni',
    'Galbeni (Nicolae Balcescu)': 'Galbeni',
    'Gura Vaii (Racova)': function () {
      throw 'Unavailable destination'
    },
    'Haghiac (Dofteana)': 'Haghiac',
    'Haghiac (Rachitoasa)': 'Haghiac',
    Hemieni() {
      throw 'Unavailable destination'
    },
    'Marginea (Buhusi)': 'Marginea',
    'Marginea (Oituz)': 'Marginea',
    'Padureni (Beresti-Bistrita)': 'Padureni',
    'Padureni (Damienesti)': 'Padureni',
    'Padureni (Filipeni)': 'Padureni',
    'Padureni (Izvoru Berheciului)': 'Padureni',
    'Padureni (Margineni)': 'Padureni',
    'Pancesti (Sascut)': function () {
      throw 'Unavailable destination'
    },
    'Plopu (Darmanesti)': 'Plopu',
    'Plopu (Podu Turcului)': 'Plopu',
    'Poiana (Colonesti)': 'Poiana',
    'Poiana (Livezi)': 'Poiana',
    'Poiana (Margineni)': 'Poiana',
    'Poiana (Motoseni)': 'Poiana',
    'Poiana (Negri)': 'Poiana',
    'Poieni (Parincea)': 'Poieni',
    'Poieni (Rosiori)': 'Poieni',
    'Poieni (Targu Ocna)': 'Poieni',
    'Prajesti (Magiresti)': 'Prajesti',
    'Sarata (Nicolae Balcescu)': 'Sarata',
    'Sarata (Solont)': 'Sarata',
    'Satu Nou (Colonesti)': 'Satu Nou',
    'Satu Nou (Lipova)': 'Satu Nou',
    'Satu Nou (Oncesti)': 'Satu Nou',
    'Satu Nou (Pargaresti)': 'Satu Nou',
    'Satu Nou (Parincea)': 'Satu Nou',
    'Satu Nou (Urechesti)': 'Satu Nou',
    'Schineni (Sascut)': 'Schineni',
    'Schineni (Saucesti)': 'Schineni',
    'Siretu (Letea Veche)': 'Siretu',
    'Siretu (Saucesti)': 'Siretu',
    'Slobozia (Filipeni)': 'Slobozia',
    'Slobozia (Onesti)': 'Slobozia',
    'Slobozia (Stanisesti)': 'Slobozia',
    'Slobozia (Urechesti)': 'Slobozia',
    'Ungureni (Tatarasti)': function () {
      throw 'Unavailable destination'
    },
    'Valcele (Corbasca)': 'Valcele',
    'Valcele (Targu Ocna)': 'Valcele',
    'Valea Mare (Colonesti)': 'Valea Mare',
    'Valea Mare (Rosiori)': 'Valea Mare',
    'Valea Mica (Cleja)': 'Valea Mica',
    'Valea Mica (Rosiori)': 'Valea Mica',
    'Valea Seaca (Nicolae Balcescu)': 'Valea Seaca',
    'Valeni (Parincea)': 'Valeni',
    'Valeni (Secuieni)': 'Valeni',
    'Valeni (Stanisesti)': 'Valeni',
    'Viisoara (Stefan cel Mare)': 'Viisoara',
    'Viisoara (Targu Trotus)': function () {
      throw 'Unavailable destination'
    },
    'Zapodia (Colonesti)': 'Zapodia',
    'Zapodia (Traian)': 'Zapodia',
  },
  BH: {
    'Almasu Mic (Balc)': 'Almasu Mic',
    'Almasu Mic (Sarbi)': 'Almasu Mic',
    'Brusturi (Finis)': 'Brusturi',
    'Gurbesti (Cabesti)': 'Gurbesti',
    'Gurbesti (Spinus)': 'Gurbesti',
    'Josani (Cabesti)': 'Josani',
    'Josani (Magesti)': 'Josani',
    Pacalesti() {
      throw 'Unavailable destination'
    },
    'Poiana (Cristioru de Jos)': 'Poiana',
    'Poiana (Tauteu)': 'Poiana',
    'Voivozi (Popesti)': 'Voivozi',
    'Voivozi (Simian)': 'Voivozi',
  },
  BN: {
    'Dumbrava (Livezile)': 'Dumbrava',
    'Dumbrava (Nuseni)': 'Dumbrava',
    'Valea Mare (Sant)': 'Valea Mare',
    'Valea Mare (Urmenis)': 'Valea Mare',
  },
  BT: {
    'Baranca (Cristinesti)': 'Baranca',
    'Baranca (Hudesti)': 'Baranca',
    'Calinesti (Bucecea)': 'Calinesti',
    'Calinesti (Candesti)': 'Calinesti',
    'Calinesti (Mihaileni)': function () {
      throw 'Unavailable destination'
    },
    Damileni() {
      throw 'Unavailable destination'
    },
    'Dobrinauti-Hapai': function () {
      throw 'Unavailable destination'
    },
    'Dragalina (Cristinesti)': 'Dragalina',
    'Dragalina (Hlipiceni)': 'Dragalina',
    'Durnesti (Santa Mare)': 'Durnesti',
    'Durnesti (Ungureni)': function () {
      throw 'Unavailable destination'
    },
    'Ionaseni (Trusesti)': 'Ionaseni',
    'Ionaseni (Varfu Campului)': 'Ionaseni',
    'Lunca (Varfu Campului)': 'Lunca',
    Maghera() {
      throw 'Unavailable destination'
    },
    'Mandresti (Ungureni)': 'Mandresti',
    'Mandresti (Vladeni)': 'Mandresti',
    'Mihai Eminescu (Gorbanesti)': function () {
      throw 'Unavailable destination'
    },
    'Mitoc (Leorda)': function () {
      throw 'Unavailable destination'
    },
    'Nicolae Balcescu (Cotusca)': 'Nicolae Balcescu',
    'Nicolae Balcescu (Flamanzi)': 'Nicolae Balcescu',
    'Padureni (Cosula)': 'Padureni',
    'Padureni (Sendriceni)': 'Padureni',
    'Poiana (Braesti)': 'Poiana',
    'Poiana (Cristinesti)': 'Poiana',
    'Poiana (Flamanzi)': 'Poiana',
    'Poiana (Vorona)': 'Poiana',
    'Popeni (Braesti)': 'Popeni',
    'Popeni (George Enescu)': 'Popeni',
    Pustoaia() {
      throw 'Unavailable destination'
    },
    'Rediu (Radauti-Prut)': 'Rediu',
    'Rediu (Rauseni)': 'Rediu',
    Sarata() {
      throw 'Unavailable destination'
    },
    'Slobozia (Broscauti)': 'Slobozia',
    'Slobozia (Cordareni)': 'Slobozia',
    'Slobozia (Paltinis)': function () {
      throw 'Unavailable destination'
    },
    'Stanca (George Enescu)': 'Stanca',
    'Stanca (Stefanesti)': 'Stanca',
    'Tudor Vladimirescu (Albesti)': 'Tudor Vladimirescu',
    'Tudor Vladimirescu (Avrameni)': 'Tudor Vladimirescu',
    Vatra() {
      throw 'Unavailable destination'
    },
    'Victoria (Hlipiceni)': 'Victoria',
    'Victoria (Stauceni)': 'Victoria',
    'Vladeni (Corlateni)': 'Vladeni',
  },
  BR: {
    Agaua() {
      throw 'Unavailable destination'
    },
    Bandoiu() {
      throw 'Unavailable destination'
    },
    'Cuza Voda (Salcia Tudor)': 'Cuza Voda',
    'Cuza Voda (Stancuta)': 'Cuza Voda',
    Frecatei() {
      throw 'Unavailable destination'
    },
    Magureni() {
      throw 'Unavailable destination'
    },
    Marasu() {
      throw 'Unavailable destination'
    },
    'Mihail Kogalniceanu (Ramnicelu)': 'Mihail Kogalniceanu',
    'Mihail Kogalniceanu (Sutesti)': 'Mihail Kogalniceanu',
    Nedelcu() {
      throw 'Unavailable destination'
    },
    Plasoiu() {
      throw 'Unavailable destination'
    },
    Plopi() {
      throw 'Unavailable destination'
    },
    Tacau() {
      throw 'Unavailable destination'
    },
  },
  BV: {
    Bradet() {
      throw 'Unavailable destination'
    },
    'Feldioara (Ucea)': 'Feldioara',
  },
  B: {
    'Sector 1': 'Sectorul 1',
    'Sector 2': 'Sectorul 2',
    'Sector 3': 'Sectorul 3',
    'Sector 4': 'Sectorul 4',
    'Sector 5': 'Sectorul 5',
    'Sector 6': 'Sectorul 6',
  },
  BZ: {
    'Corbu (Catina)': 'Corbu',
    'Corbu (Glodeanu-Silistea)': 'Corbu',
    'Fantanele (Margaritesti)': 'Fantanele',
    'Fantanele (Naeni)': 'Fantanele',
    'Izvoru (Cozieni)': 'Izvoru',
    'Izvoru (Tisau)': 'Izvoru',
    'Izvoru Dulce (Beceni)': 'Izvoru Dulce',
    'Izvoru Dulce (Merei)': 'Izvoru Dulce',
    'Lunca (Amaru)': 'Lunca',
    'Lunca (C.A. Rosetti)': 'Lunca',
    'Lunca (Patarlagele)': 'Lunca',
    'Lunca (Puiesti)': 'Lunca',
    Ojasca() {
      throw 'Unavailable destination'
    },
    'Plesesti (Berca)': 'Plesesti',
    'Plesesti (Podgoria)': 'Plesesti',
    'Posta (Cilibia)': 'Posta',
    'Posta (Topliceni)': 'Posta',
    'Satu Nou (Glodeanu-Silistea)': 'Satu Nou',
    'Satu Nou (Mihailesti)': 'Satu Nou',
    'Suditi (Gheraseni)': 'Suditi',
    'Suditi (Posta Calnau)': 'Suditi',
    'Trestioara (Chiliile)': 'Trestioara',
    'Trestioara (Manzalesti)': 'Trestioara',
  },
  CL: {
    'Alexandru I. Cuza': 'Alexandru Ioan Cuza',
    'Chirnogi (Ulmu)': 'Chirnogi',
    'Dorobantu (Plataresti)': 'Dorobantu',
    'Nicolae Balcescu (Alexandru Odobescu)': 'Nicolae Balcescu',
  },
  CS: {
    'Cuptoare (Cornea)': 'Cuptoare',
    'Cuptoare (Resita)': 'Cuptoare',
    'Macoviste (Ciuchici)': 'Macoviste',
    'Macoviste (Cornea)': function () {
      throw 'Unavailable destination'
    },
    'Prislop (Cornereva)': 'Prislop',
    'Prislop (Dalboset)': 'Prislop',
  },
  CJ: {
    'Balcesti (Belis)': 'Balcesti',
    'Balcesti (Capusu Mare)': 'Balcesti',
    'Cornesti (Garbau)': 'Cornesti',
    'Cornesti (Mihai Viteazu)': 'Cornesti',
    'Hasdate (Gherla)': 'Hasdate',
    'Hasdate (Savadisla)': 'Hasdate',
    'Livada (Iclod)': 'Livada',
    'Livada (Petrestii de Jos)': 'Livada',
    'Padureni (Chinteni)': 'Padureni',
    'Padureni (Ciurila)': 'Padureni',
    'Padurenii (Mintiu Gherlii)': 'Padurenii',
    'Padurenii (Tritenii de Jos)': 'Padurenii',
    Risca() {
      throw 'Unavailable destination'
    },
    'Sanmartin (Chinteni)': 'Sanmartin',
    'Straja (Capusu Mare)': 'Straja',
    'Straja (Cojocna)': 'Straja',
    'Valeni (Caianu)': 'Valeni',
    'Valeni (Calatele)': 'Valeni',
  },
  CT: {
    Aurora() {
      throw 'Unavailable destination'
    },
    Basarabi() {
      throw 'Unavailable destination'
    },
    Culmea() {
      throw 'Unavailable destination'
    },
    Murfatlar: 'Murfatlar (Basarabi)',
    'Satu Nou (Mircea Voda)': 'Satu Nou',
    'Satu Nou (Oltina)': 'Satu Nou',
  },
  CV: {
    'Baile Balvanyos': function () {
      throw 'Unavailable destination'
    },
    Tinoasa() {
      throw 'Unavailable destination'
    },
  },
  DB: {
    'Brosteni (Bezdead)': 'Brosteni',
    'Brosteni (Produlesti)': 'Brosteni',
    'Brosteni (Visina)': 'Brosteni',
    'Calugareni (Cobia)': 'Calugareni',
    'Calugareni (Contesti)': 'Calugareni',
    'Catunu (Cornesti)': 'Catunu',
    'Catunu (Salcioara)': 'Catunu',
    'Glodeni (Pucioasa)': 'Glodeni',
    'Izvoru (Valea Lunga)': 'Izvoru',
    'Izvoru (Visina)': 'Izvoru',
    'Livezile (Glodeni)': 'Livezile',
    'Livezile (Valea Mare)': 'Livezile',
    'Lunca (Moroeni)': 'Lunca',
    'Lunca (Voinesti)': 'Lunca',
    'Magura (Bezdead)': 'Magura',
    'Magura (Hulubesti)': 'Magura',
    Manastirea() {
      throw 'Unavailable destination'
    },
    'Mereni (Contesti)': 'Mereni',
    'Mereni (Titu)': 'Mereni',
    'Movila (Niculesti)': 'Movila',
    'Movila (Salcioara)': 'Movila',
    'Olteni (Lucieni)': 'Olteni',
    'Olteni (Uliesti)': 'Olteni',
    'Petresti (Corbii Mari)': 'Petresti',
    'Priboiu (Branesti)': 'Priboiu',
    'Priboiu (Tatarani)': 'Priboiu',
    'Pucheni (Moroeni)': 'Pucheni',
    'Rau Alb': function () {
      throw 'Unavailable destination'
    },
    'Salcioara (Matasaru)': 'Salcioara',
    'Silistea (Raciu)': 'Silistea',
    'Silistea (Runcu)': 'Silistea',
    'Ungureni (Butimanu)': 'Ungureni',
    'Ungureni (Corbii Mari)': 'Ungureni',
    'Ungureni (Cornesti)': 'Ungureni',
    'Ungureni (Dragomiresti)': 'Ungureni',
    'Valea Mare (Candesti)': 'Valea Mare',
    'Valea Mare (Valea Lunga)': 'Valea Mare',
  },
  DJ: {
    'Bechet (Orodel)': 'Bechet',
    'Braniste (Daneti)': 'Braniste',
    'Braniste (Filiasi)': 'Braniste',
    'Braniste (Podari)': 'Braniste',
    Cernele() {
      throw 'Unavailable destination'
    },
    'Cetatuia (Cioroiasi)': 'Cetatuia',
    'Cetatuia (Vela)': 'Cetatuia',
    'Fantanele (Radovan)': 'Fantanele',
    'Fantanele (Teslui)': 'Fantanele',
    Rovine() {
      throw 'Unavailable destination'
    },
    'Salcuta (Calopar)': 'Salcuta',
  },
  GL: {
    'Branistea (Nicoresti)': 'Branistea',
    'Liesti (Priponesti)': 'Liesti',
    'Movileni (Sendreni)': 'Movileni',
    'Umbraresti (Targu Bujor)': 'Umbraresti',
  },
  GR: {
    'Cascioarele (Gaiseni)': 'Cascioarele',
    'Cascioarele (Ulmi)': 'Cascioarele',
    Comasca() {
      throw 'Unavailable destination'
    },
    Isvoarele: 'Izvoarele',
    'Izvoru (Gogosari)': 'Izvoru',
    'Izvoru (Vanatorii Mici)': 'Izvoru',
    'Sfantu Gheorghe (Baneasa)': 'Sfantu Gheorghe',
    'Sfantu Gheorghe (Crevedia Mare)': 'Sfantu Gheorghe',
    'Stoenesti (Floresti-Stoenesti)': 'Stoenesti',
  },
  GJ: {
    Insuratei() {
      throw 'Unavailable destination'
    },
    Lainici() {
      throw 'Unavailable destination'
    },
    Vart() {
      throw 'Unavailable destination'
    },
  },
  HR: {
    'Bucin (Joseni)': 'Bucin',
    'Bucin (Praid)': 'Bucin',
    'Fagetel (Frumoasa)': 'Fagetel',
    'Fagetel (Remetea)': 'Fagetel',
    'Garciu (Racu)': function () {
      throw 'Unavailable destination'
    },
    'Mihaileni (Simonesti)': function () {
      throw 'Unavailable destination'
    },
    'Nicolesti (Frumoasa)': 'Nicolesti',
    'Nicolesti (Ulies)': 'Nicolesti',
    Porumbeni() {
      throw 'Unavailable destination'
    },
    'Satu Nou (Ocland)': 'Satu Nou',
    'Satu Nou (Racu)': 'Satu Nou',
  },
  HD: {
    'Alun (Bosorod)': 'Alun',
    'Alun (Bunila)': 'Alun',
    'Lunca (Baia de Cris)': 'Lunca',
    'Lunca (Baita)': 'Lunca',
    'Merisor (Banita)': 'Merisor',
    'Merisor (Bucuresci)': 'Merisor',
    'Mesteacan (Brad)': 'Mesteacan',
    'Mesteacan (Rachitova)': 'Mesteacan',
    'Pestera (Baita)': 'Pestera',
    'Pestera (Petrosani)': 'Pestera',
    'Pestera (Salasu de Sus)': 'Pestera',
    'Poieni (Beriu)': 'Poieni',
    'Poieni (Densus)': 'Poieni',
    'Prihodiste (Bosorod)': 'Prihodiste',
    'Prihodiste (Vata de Jos)': 'Prihodiste',
    'Radulesti (Stancesti)': 'Radulesti',
    'Rovina (Branisca)': 'Rovina',
    'Rovina (Bucuresci)': 'Rovina',
    'Sibisel (Beriu)': 'Sibisel',
    'Sibisel (Rau de Mori)': 'Sibisel',
    'Valeni (Baia de Cris)': 'Valeni',
    'Valeni (Geoagiu)': 'Valeni',
    'Valisoara (Balsa)': 'Valisoara',
  },
  IL: {
    Baraganu() {
      throw 'Unavailable destination'
    },
  },
  IS: {
    'Alexandru I. Cuza': 'Alexandru Ioan Cuza',
    'Baiceni (Cucuteni)': 'Baiceni',
    'Baiceni (Todiresti)': 'Baiceni',
    'Boureni (Bals)': 'Boureni',
    'Boureni (Motca)': 'Boureni',
    'Buda (Braesti)': 'Buda',
    'Buda (Lespezi)': 'Buda',
    'Cozmesti (Stolniceni-Prajescu)': 'Cozmesti',
    'Cristesti (Braesti)': 'Cristesti',
    'Cristesti (Holboca)': 'Crivesti',
    'Crivesti (Strunga)': 'Crivesti',
    'Crivesti (Vanatori)': function () {
      throw 'Unavailable destination'
    },
    'Cucuteni (Letcani)': 'Cucuteni',
    'Cuza Voda (Ipatele)': 'Cuza Voda',
    'Cuza Voda (Popricani)': 'Cuza Voda',
    'Deleni (Ciortesti)': 'Deleni',
    'Dumbrava (Ciurea)': 'Dumbrava',
    'Dumbrava (Lespezi)': 'Dumbrava',
    'Fantanele (Andrieseni)': 'Fantanele',
    Harmanesti() {
      throw 'Unavailable destination'
    },
    'Horlesti (Rediu)': 'Horlesti',
    'Iepureni (Andrieseni)': 'Iepureni',
    'Iepureni (Movileni)': 'Iepureni',
    'Lunca (Grajduri)': 'Lunca',
    'Lunca (Pascani)': 'Lunca',
    'Lungani (Voinesti)': 'Lungani',
    'Movileni (Helesteni)': function () {
      throw 'Unavailable destination'
    },
    'Osoi (Comarna)': 'Osoi',
    'Osoi (Sinesti)': 'Osoi',
    'Padureni (Grajduri)': 'Padureni',
    'Padureni (Popesti)': 'Padureni',
    'Poiana (Deleni)': 'Poiana',
    'Poiana (Schitu Duca)': 'Poiana',
    'Rediu (Braesti)': 'Rediu',
    'Rediu (Ruginoasa)': 'Rediu',
    'Rediu (Scanteia)': 'Rediu',
    'Satu Nou (Belcesti)': 'Satu Nou',
    'Satu Nou (Scheia)': 'Satu Nou',
    'Satu Nou (Siretel)': 'Satu Nou',
    Scheia() {
      throw 'Unavailable destination'
    },
    'Scoposeni (Gorban)': 'Scoposeni',
    'Scoposeni (Horlesti)': 'Scoposeni',
    'Slobozia (Ciurea)': 'Slobozia',
    'Slobozia (Deleni)': 'Slobozia',
    'Slobozia (Schitu Duca)': 'Slobozia',
    'Slobozia (Siretel)': 'Slobozia',
    'Slobozia (Voinesti)': 'Slobozia',
    'Stanca (Comarna)': 'Stanca',
    'Stanca (Victoria)': 'Stanca',
    'Tansa (Belcesti)': 'Tansa',
    'Vanatori (Popricani)': 'Vanatori',
  },
  IF: {
    'Pipera (Voluntari)': function () {
      throw 'Unavailable destination'
    },
  },
  MM: {
    'Sarbi (Budesti)': 'Sarbi',
    'Sarbi (Farcasa)': 'Sarbi',
  },
  MH: {
    'Baltanele (Greci)': 'Baltanele',
    'Baltanele (Prunisor)': 'Baltanele',
    'Godeanu (Obarsia-Closani)': 'Godeanu',
    'Sipotu (Ponoarele)': 'Sipotu',
    'Sipotu (Poroina Mare)': 'Sipotu',
    'Stefan Odobleja': function () {
      throw 'Unavailable destination'
    },
    'Susita (Breznita-Ocol)': 'Susita',
    'Susita (Grozesti)': 'Susita',
    'Valea Ursului (Ponoarele)': 'Valea Ursului',
    'Valea Ursului (Tamna)': 'Valea Ursului',
  },
  MS: {
    Ciba() {
      throw 'Unavailable destination'
    },
    'Cornesti (Adamus)': 'Cornesti',
    'Cornesti (Craciunesti)': 'Cornesti',
    'Craiesti (Adamus)': 'Craiesti',
    'Daia (Apold)': 'Daia',
    'Daia (Bahnea)': 'Daia',
    'Deleni (Ideciu de Jos)': 'Deleni',
    'Deleni (Pogaceaua)': 'Deleni',
    'Dupa Deal (Cuci)': 'Dupa Deal',
    'Dupa Deal (Iclanzel)': 'Dupa Deal',
    'Fanate (Band)': 'Fanate',
    'Fanate (Faragau)': 'Fanate',
    'Fanate (Iclanzel)': 'Fanate',
    'Fanate (Taureni)': 'Fanate',
    Foi() {
      throw 'Unavailable destination'
    },
    'Larga (Gurghiu)': 'Larga',
    'Larga (Sarmasu)': 'Larga',
    Nicolesti() {
      throw 'Unavailable destination'
    },
    'Parau Crucii (Pogaceaua)': 'Parau Crucii',
    'Parau Crucii (Raciu)': 'Parau Crucii',
    'Satu Nou (Gheorghe Doja)': 'Satu Nou',
    'Satu Nou (Sanpetru de Campie)': 'Satu Nou',
    'Seleus (Danes)': 'Seleus',
    'Seleus (Zagar)': 'Seleus',
    Seuca() {
      throw 'Unavailable destination'
    },
    'Valea Sanpetrului (Grebenisu de Campie)': 'Valea Sanpetrului',
    'Valea Sanpetrului (Pogaceaua)': 'Valea Sanpetrului',
  },
  NT: {
    'Balusesti (Dochia)': 'Balusesti',
    'Balusesti (Icusesti)': 'Balusesti',
    Botesti() {
      throw 'Unavailable destination'
    },
    'Botesti (Girov)': function () {
      throw 'Unavailable destination'
    },
    'Izvoare (Bahna)': 'Izvoare',
    'Izvoare (Dumbrava Rosie)': 'Izvoare',
    'Lunca (Borca)': 'Lunca',
    'Lunca (Oniceni)': 'Lunca',
    'Lunca (Vanatori-Neamt)': 'Lunca',
    'Mastacan (Borlesti)': 'Mastacan',
    'Mastacan (Dragomiresti)': 'Mastacan',
    'Negresti (Bara)': function () {
      throw 'Unavailable destination'
    },
    'Piatra-Neamt': 'Piatra Neamt',
    'Poiana (Brusturi)': 'Poiana',
    'Poiana (Dulcesti)': 'Poiana',
    'Poiana (Grinties)': 'Poiana',
    'Poiana (Negresti)': 'Poiana',
    'Poiana (Pangarati)': 'Poiana',
    'Popesti (Farcasa)': 'Popesti',
    'Popesti (Girov)': 'Popesti',
    'Rediu (Bara)': function () {
      throw 'Unavailable destination'
    },
    'Ruseni (Borlesti)': 'Ruseni',
    'Ruseni (Poiana Teiului)': 'Ruseni',
    'Savinesti (Poiana Teiului)': 'Savinesti',
    'Slobozia (Boghicea)': 'Slobozia',
    'Slobozia (Roznov)': 'Slobozia',
    'Soci (Borca)': 'Soci',
    'Soci (Stefan cel Mare)': 'Soci',
    'Stejaru (Farcasa)': 'Stejaru',
    'Stejaru (Ion Creanga)': 'Stejaru',
    'Stejaru (Pangarati)': 'Stejaru',
    'Traian (Sabaoani)': 'Traian',
    'Traian (Zanesti)': 'Traian',
    'Vadurele (Alexandru cel Bun)': 'Vadurele',
    'Vadurele (Candesti)': 'Vadurele',
    'Valeni (Piatra-Neamt)': 'Valeni',
  },
  OT: {
    'Barasti (Colonesti)': 'Barasti',
    'Barasti (Morunglav)': 'Barasti',
    Barza() {
      throw 'Unavailable destination'
    },
    'Corbu (Teslui)': 'Corbu',
    'Curtisoara (Dobretu)': 'Curtisoara',
    'Greci (Osica de Sus)': 'Greci',
    'Greci (Schitu)': 'Greci',
    'Magura (Perieti)': 'Magura',
    'Magura (Tatulesti)': 'Magura',
    'Maruntei (Colonesti)': 'Maruntei',
    'Popesti (Barasti)': 'Popesti',
    'Popesti (Valeni)': 'Popesti',
    'Sarbii-Magura': function () {
      throw 'Unavailable destination'
    },
    'Satu Nou (Gradinari)': 'Satu Nou',
    'Satu Nou (Gura Padinii)': 'Satu Nou',
    'Seaca (Poboru)': 'Seaca',
    'Stanuleasa (Samburesti)': 'Stanuleasa',
    'Stanuleasa (Vitomiresti)': 'Stanuleasa',
    'Tonesti (Leleasca)': 'Tonesti',
    'Tonesti (Samburesti)': 'Tonesti',
    'Valeni (Brancoveni)': 'Valeni',
  },
  PH: {
    'Buda (Aricestii Rahtivani)': 'Buda',
    'Buda (Rafov)': 'Buda',
    'Catunu (Berceni)': 'Catunu',
    'Catunu (Drajna)': 'Catunu',
    'Cornu de Jos (Cornu)': 'Cornu de Jos',
    'Cornu de Jos (Draganesti)': 'Cornu de Jos',
    'Cornu de Sus (Cornu)': 'Cornu de Sus',
    'Cornu de Sus (Dumbrava)': 'Cornu de Sus',
    'Fanari (Gorgota)': 'Fanari',
    'Fanari (Olari)': 'Fanari',
    'Nucet (Chiojdeanca)': 'Nucet',
    'Nucet (Gornet)': 'Nucet',
    'Persunari (Cocorastii Colt)': 'Persunari',
    'Persunari (Gura Vadului)': 'Persunari',
    'Piatra (Cocorastii Colt)': 'Piatra',
    'Piatra (Drajna)': 'Piatra',
    'Piatra (Provita de Jos)': 'Piatra',
    'Plaiu (Provita de Sus)': 'Plaiu',
    'Plaiu (Talea)': 'Plaiu',
    'Plopeni (Dumbravesti)': 'Plopeni',
    'Popesti (Brazi)': 'Popesti',
    'Popesti (Podenii Noi)': 'Popesti',
    'Satu Nou (Baba Ana)': 'Satu Nou',
    'Satu Nou (Lipanesti)': 'Satu Nou',
    'Schiau (Urlati)': 'Schiau',
    'Schiau (Valea Calugareasca)': 'Schiau',
    'Ungureni (Filipestii de Targ)': 'Ungureni',
    'Ungureni (Gherghita)': 'Ungureni',
    'Ungureni (Vadu Sapat)': 'Ungureni',
  },
  SJ: {
    Dabaceni: 'Dabiceni',
    'Stana (Zalau)': function () {
      throw 'Unavailable destination'
    },
  },
  SM: {},
  SB: {
    'Balea Lac': function () {
      throw 'Unavailable destination'
    },
    'Veseud (Chirpar)': 'Veseud',
    'Veseud (Slimnic)': 'Veseud',
  },
  SV: {
    'Brodina (Izvoarele Sucevei)': 'Brodina',
    'Brosteni (Draguseni)': 'Brosteni',
    'Buda (Rasca)': 'Buda',
    'Buda (Zvoristea)': 'Buda',
    'Calinesti (Darmanesti)': 'Calinesti',
    'Calinesti (Serbauti)': 'Calinesti',
    Darmoxa: 'Darmova',
    'Dumbrava (Cornu Luncii)': 'Dumbrava',
    'Dumbrava (Granicesti)': 'Dumbrava',
    'Dumbraveni (Rasca)': 'Dumbraveni',
    'Frasin (Brosteni)': 'Frasin',
    'Liteni (Moara)': 'Liteni',
    'Lunca (Milisauti)': 'Lunca',
    'Lunca (Zamostea)': 'Lunca',
    'Manastioara (Siret)': 'Manastioara',
    'Manastioara (Udesti)': 'Manastioara',
    Obcina: 'Obcina Ursului',
    'Poiana (Dolhasca)': 'Poiana',
    'Poiana (Zvoristea)': 'Poiana',
    'Romanesti (Cosna)': 'Romanesti',
    'Romanesti (Granicesti)': 'Romanesti',
    'Satu Mare (Crucea)': 'Satu Mare',
    'Slatioara (Rasca)': 'Slatioara',
    'Slatioara (Stulpicani)': 'Slatioara',
    'Slobozia (Fantanele)': 'Slobozia',
    'Slobozia (Zvoristea)': 'Slobozia',
    'Tesna (Cosna)': 'Tesna',
    'Tesna (Poiana Stampei)': 'Tesna',
  },
  TR: {
    'Bujoru (Calmatuiu)': 'Bujoru',
    'Ciuperceni (Cosmesti)': 'Ciuperceni',
    'Merisani (Babaita)': 'Merisani',
    'Merisani (Dobrotesti)': 'Merisani',
    'Mosteni (Furculesti)': 'Mosteni',
    'Purani (Vitanesti)': 'Purani',
    'Silistea (Vitanesti)': 'Silistea',
    'Stejaru (Crangeni)': 'Stejaru',
  },
  TM: {
    'Bucovat (Dumbrava)': 'Bucovat',
    'Bucovat (Remetea Mare)': 'Bucovat',
    Florica() {
      throw 'Unavailable destination'
    },
    'Hodos (Brestovat)': 'Hodos',
    'Hodos (Darova)': 'Hodos',
    'Padureni (Victor Vlad Delamarina)': 'Padureni',
  },
  TL: {
    'Baltenii de Jos': function () {
      throw 'Unavailable destination'
    },
    'C.A. Rosetti': function () {
      throw 'Unavailable destination'
    },
    Caraorman() {
      throw 'Unavailable destination'
    },
    Cardon() {
      throw 'Unavailable destination'
    },
    Ceatalchioi() {
      throw 'Unavailable destination'
    },
    'Chilia Veche': function () {
      throw 'Unavailable destination'
    },
    Crisan() {
      throw 'Unavailable destination'
    },
    Gorgova() {
      throw 'Unavailable destination'
    },
    'Ilganii de Jos': function () {
      throw 'Unavailable destination'
    },
    'Ilganii de Sus': function () {
      throw 'Unavailable destination'
    },
    Letea() {
      throw 'Unavailable destination'
    },
    Maliuc() {
      throw 'Unavailable destination'
    },
    'Mila 23': function () {
      throw 'Unavailable destination'
    },
    'Ostrov Tataru': function () {
      throw 'Unavailable destination'
    },
    Pardina() {
      throw 'Unavailable destination'
    },
    Partizani() {
      throw 'Unavailable destination'
    },
    Patlageanca() {
      throw 'Unavailable destination'
    },
    Periprava() {
      throw 'Unavailable destination'
    },
    Plauru() {
      throw 'Unavailable destination'
    },
    Salceni() {
      throw 'Unavailable destination'
    },
    'Sfantu Gheorghe': function () {
      throw 'Unavailable destination'
    },
    Sfistofca() {
      throw 'Unavailable destination'
    },
    Sulina() {
      throw 'Unavailable destination'
    },
    Tatanir() {
      throw 'Unavailable destination'
    },
  },
  VL: {
    'Barsesti (Budesti)': 'Barsesti',
    'Barsesti (Mihaesti)': 'Barsesti',
    'Berbesti (Lalosu)': 'Berbesti',
    'Bodesti (Alunu)': 'Bodesti',
    'Bodesti (Barbatesti)': 'Bodesti',
    'Bogdanesti (Bujoreni)': 'Bogdanesti',
    'Bogdanesti (Otesani)': 'Bogdanesti',
    'Bogdanesti (Tomsani)': 'Bogdanesti',
    'Budesti (Diculesti)': 'Budesti',
    Budurasti: 'Budesti',
    Bujoreni: 'Budurasti',
    Bulagei: 'Bujoreni',
    Buleta: 'Bulagei',
    Bumbuesti: 'Buleta',
    Bunesti: 'Bumbuesti',
    Bungetani: 'Bunesti',
    Burdalesti: 'Bungetani',
    Butanu: 'Burdalesti',
    Buzdugan: 'Butanu',
    Caciulata: 'Buzdugan',
    Caineni: 'Caciulata',
    'Cainenii Mari': 'Caineni',
    'Cainenii Mici': 'Cainenii Mari',
    Caligi: 'Cainenii Mici',
    Calimanesti: 'Caligi',
    Calina: 'Calimanesti',
    Calinesti: 'Calina',
    'Capu Dealului': 'Calinesti',
    Carcadiesti: 'Capu Dealului',
    Carlogani: 'Carcadiesti',
    Carstanesti: 'Carlogani',
    'Casa Veche': 'Carstanesti',
    Catetu: 'Casa Veche',
    'Cazanesti (Ghioroiu)': 'Catetu',
    'Cazanesti (Milcoiu)': 'Cazanesti',
    'Cazanesti (Ramnicu Valcea)': 'Cazanesti',
    Ceretu: 'Cazanesti',
    'Cermegesti (Ladesti)': 'Ceretu',
    'Cermegesti (Pesceana)': 'Cermegesti',
    Cerna: 'Cermegesti',
    Cernelele: 'Cerna',
    Cernisoara: 'Cernelele',
    Cetateaua: 'Cernisoara',
    Cheia: 'Cetateaua',
    Cherasti: 'Cheia',
    Chiceni: 'Cherasti',
    Chirculesti: 'Chiceni',
    Chiricesti: 'Chirculesti',
    Cioboti: 'Chiricesti',
    Ciocaltei: 'Cioboti',
    Ciocanari: 'Ciocaltei',
    Cioponesti: 'Ciocanari',
    Ciorasti: 'Cioponesti',
    Ciortesti: 'Ciorasti',
    Ciresu: 'Ciortesti',
    Ciresul: 'Ciresu',
    Ciucheti: 'Ciresul',
    Ciumagi: 'Ciucheti',
    Ciungetu: 'Ciumagi',
    Ciutesti: 'Ciungetu',
    'Coasta (Golesti)': 'Ciutesti',
    'Coasta (Pausesti-Maglasi)': 'Coasta',
    'Coasta Cerbului': 'Coasta',
    'Coasta Mare': 'Coasta Cerbului',
    Cocoru: 'Coasta Mare',
    Colelia: 'Cocoru',
    Coltesti: 'Colelia',
    Comanca: 'Coltesti',
    Condoiesti: 'Comanca',
    Contea: 'Condoiesti',
    Copacelu: 'Contea',
    Copaceni: 'Copacelu',
    'Copaceni (Racovita)': 'Copaceni',
    'Corbii din Vale': 'Copaceni',
    Corbu: 'Corbii din Vale',
    Cornet: 'Corbu',
    Cosani: 'Cornet',
    Cosota: 'Cosani',
    Costesti: 'Cosota',
    Crangu: 'Costesti',
    Cremenari: 'Crangu',
    Creteni: 'Cremenari',
    Cucesti: 'Creteni',
    Cuci: 'Cucesti',
    Cucoiu: 'Cuci',
    Cuculesti: 'Cucoiu',
    Cueni: 'Cuculesti',
    Curaturile: 'Cueni',
    Curtea: 'Curaturile',
    Daesti: 'Curtea',
    'Daesti (Popesti)': 'Daesti',
    Damteni: 'Daesti',
    Dancai: 'Damteni',
    Dangesti: 'Dancai',
    Danicei: 'Dangesti',
    'Dealu Alunis': 'Danicei',
    'Dealu Bisericii': 'Dealu Alunis',
    'Dealu Corni': 'Dealu Bisericii',
    'Dealu Glameia': 'Dealu Corni',
    'Dealu Launele': 'Dealu Glameia',
    'Dealu Malului': 'Dealu Launele',
    'Dealu Mare (Galicea)': 'Dealu Malului',
    'Dealu Mare (Gusoeni)': 'Dealu Mare',
    'Dealu Mare (Ionesti)': 'Dealu Mare',
    'Dealu Scheiului': 'Dealu Mare',
    'Dealu Valeni': 'Dealu Scheiului',
    Dejoi: 'Dealu Valeni',
    Deleni: 'Dejoi',
    'Delureni (Ionesti)': 'Deleni',
    'Delureni (Stoilesti)': 'Delureni',
    'Delureni (Valea Mare)': 'Delureni',
    Dezrobiti: 'Delureni',
    Diaconesti: 'Dezrobiti',
    Dianu: 'Diaconesti',
    Diculesti: 'Dianu',
    Dimulesti: 'Diculesti',
    Dobresti: 'Dimulesti',
    Dobricea: 'Dobresti',
    Dobriceni: 'Dobricea',
    Dobrusa: 'Dobriceni',
    'Dosu Raului': 'Dobrusa',
    Dozesti: 'Dosu Raului',
    'Draganesti (Brezoi)': 'Dozesti',
    'Draganesti (Golesti)': 'Draganesti',
    Draganu: 'Draganesti',
    Dragasani: 'Draganu',
    Dragioiu: 'Dragasani',
    Dragoesti: 'Dragioiu',
    Dragulesti: 'Dragoesti',
    Dumbrava: 'Dragulesti',
    Dumbravesti: 'Dumbrava',
    Facai: 'Dumbravesti',
    Fartatesti: 'Facai',
    Fauresti: 'Fartatesti',
    'Fauresti (Zatreni)': 'Fauresti',
    Fedelesoiu: 'Fauresti',
    Feteni: 'Fedelesoiu',
    'Geamana (Dragoesti)': 'Geamana',
    'Geamana (Stoilesti)': 'Geamana',
    Goranu() {
      throw 'Unavailable destination'
    },
    'Gorunesti (Balcesti)': 'Gorunesti',
    'Gorunesti (Slatioara)': 'Gorunesti',
    'Izvoru Rece (Stoilesti)': 'Izvoru Rece',
    'Izvoru Rece (Vaideeni)': 'Izvoru Rece',
    'Linia (Budesti)': 'Linia',
    'Linia (Gradistea)': 'Linia',
    'Lunca (Bujoreni)': 'Lunca',
    'Lunca (Ocnele Mari)': 'Lunca',
    'Madulari (Cernisoara)': 'Madulari',
    'Maldaresti (Ladesti)': 'Maldaresti',
    'Maldaresti (Maciuca)': function () {
      throw 'Unavailable destination'
    },
    'Olteanca (Glavile)': 'Olteanca',
    'Olteanca (Ladesti)': 'Olteanca',
    'Pietrari (Pausesti-Maglasi)': 'Pietrari',
    'Plesoiu (Livezi)': 'Plesoiu',
    'Plesoiu (Nicolae Balcescu)': 'Plesoiu',
    'Popesti (Fartatesti)': 'Popesti',
    'Popesti (Golesti)': 'Popesti',
    'Popesti (Ladesti)': 'Popesti',
    'Popesti (Maciuca)': 'Popesti',
    'Popesti (Nicolae Balcescu)': 'Popesti',
    'Popesti (Sinesti)': 'Popesti',
    'Popesti (Stoenesti)': 'Popesti',
    'Popesti (Tetoiu)': 'Popesti',
    'Racovita (Budesti)': 'Racovita',
    'Ramesti (Horezu)': 'Ramesti',
    'Ramesti (Susani)': 'Ramesti',
    Raureni() {
      throw 'Unavailable destination'
    },
    'Roesti (Pesceana)': function () {
      throw 'Unavailable destination'
    },
    'Rugetu (Mihaesti)': 'Rugetu',
    'Rugetu (Slatioara)': 'Rugetu',
    'Seaca (Calimanesti)': 'Seaca',
    'Seaca (Salatrucel)': 'Seaca',
    'Serbanesti (Lapusata)': 'Serbanesti',
    'Serbanesti (Pausesti)': 'Serbanesti',
    'Serbanesti (Salatrucel)': 'Serbanesti',
    'Serbanesti (Stefanesti)': 'Serbanesti',
    'Stanesti (Stoilesti)': 'Stanesti',
    'Stefanesti (Maciuca)': function () {
      throw 'Unavailable destination'
    },
    'Stoenesti (Berislavesti)': 'Stoicanesti',
    Stoicanesti: 'Stoiculesti',
    Stoiculesti() {
      throw 'Unavailable destination'
    },
    'Ursi (Popesti)': 'Ursi',
    'Ursi (Stoilesti)': 'Ursi',
    'Valea Caselor (Dragasani)': 'Valea Caselor',
    'Valea Caselor (Popesti)': 'Valea Caselor',
    'Valea Mare (Babeni)': 'Valea Mare',
    'Valea Mare (Berbesti)': 'Valea Mare',
    'Valeni (Pausesti)': 'Valeni',
    'Valeni (Zatreni)': 'Valeni',
  },
  VS: {
    'Albesti (Delesti)': 'Albesti',
    'Armaseni (Bacesti)': 'Armaseni',
    'Armaseni (Bunesti-Averesti)': 'Armaseni',
    'Bogdanesti (Falciu)': function () {
      throw 'Unavailable destination'
    },
    'Buda (Alexandru Vlahuta)': 'Buda',
    'Buda (Bogdanesti)': 'Buda',
    'Buda (Osesti)': 'Buda',
    'Coroiesti (Bogdanita)': 'Coroiesti',
    'Deleni (Hoceni)': 'Deleni',
    'Epureni (Duda-Epureni)': function () {
      throw 'Unavailable destination'
    },
    'Fundatura (Arsura)': 'Fundatura',
    'Fundatura (Delesti)': 'Fundatura',
    'Fundu Vaii (Lipovat)': 'Fundu Vaii',
    'Fundu Vaii (Poienesti)': 'Fundu Vaii',
    'Ghermanesti (Banca)': 'Ghermanesti',
    'Ghermanesti (Dranceni)': 'Ghermanesti',
    'Ivanesti (Padureni)': 'Ivanesti',
    'Leosti (Padureni)': 'Leosti',
    'Leosti (Tatarani)': 'Leosti',
    'Macresti (Rebricea)': 'Macresti',
    'Macresti (Zapodeni)': 'Macresti',
    'Manastirea (Delesti)': 'Manastirea',
    'Manastirea (Malusteni)': 'Manastirea',
    'Miclesti (Banca)': 'Miclesti',
    'Obarseni (Vinderei)': 'Obarseni',
    'Obarseni (Voinesti)': 'Obarseni',
    'Padureni (Osesti)': 'Padureni',
    'Podu Petris': 'Podu Pietris',
    'Popeni (Gagesti)': 'Popeni',
    'Popeni (Zorleni)': 'Popeni',
    'Popesti (Dragomiresti)': 'Popesti',
    'Popesti (Miclesti)': 'Popesti',
    'Rascani (Danesti)': 'Rascani',
    'Rascani (Suletea)': 'Rascani',
    'Rediu (Hoceni)': 'Rediu',
    'Rediu (Rosiesti)': 'Rediu',
    'Rediu (Vaslui)': 'Rediu',
    'Satu Nou (Banca)': 'Satu Nou',
    'Satu Nou (Berezeni)': 'Satu Nou',
    'Satu Nou (Cretesti)': 'Satu Nou',
    'Satu Nou (Muntenii de Sus)': 'Satu Nou',
    'Satu Nou (Pochidia)': 'Satu Nou',
    'Satu Nou (Solesti)': 'Satu Nou',
    'Silistea (Iana)': 'Silistea',
    'Silistea (Pungesti)': 'Silistea',
    'Silistea (Todiresti)': 'Silistea',
    'Tatarani (Danesti)': 'Tatarani',
    'Valea Mare (Dumesti)': 'Valea Mare',
    'Valea Mare (Ivanesti)': 'Valea Mare',
    'Valea Mare (Negresti)': 'Valea Mare',
    'Valeni (Padureni)': 'Valeni',
    'Valeni (Viisoara)': 'Valeni',
    'Viisoara (Todiresti)': 'Viisoara',
    'Viisoara (Vaslui)': 'Viisoara',
    'Voinesti (Vulturesti)': 'Voinesti',
  },
  VN: {
    'Blidari (Carligele)': 'Blidari',
    'Blidari (Dumitresti)': 'Blidari',
    'Costisa (Homocea)': 'Costisa',
    'Costisa (Tanasoaia)': 'Costisa',
    'Dragosloveni (Dumbraveni)': 'Dragosloveni',
    'Dragosloveni (Soveja)': 'Dragosloveni',
    'Dumbrava (Panciu)': 'Dumbrava',
    'Dumbrava (Poiana Cristei)': 'Dumbrava',
    'Nanesti (Tanasoaia)': 'Nanesti',
    'Padureni (Jaristea)': 'Padureni',
    'Padureni (Marasesti)': 'Padureni',
    'Padureni (Tamboesti)': 'Padureni',
    'Pietroasa (Bolotesti)': 'Pietroasa',
    'Pietroasa (Campineanca)': 'Pietroasa',
    'Pietroasa (Tamboesti)': 'Pietroasa',
    'Pietroasa (Vartescoiu)': 'Pietroasa',
    'Satu Nou (Ciorasti)': 'Satu Nou',
    'Satu Nou (Panciu)': 'Satu Nou',
    'Valeni (Movilita)': 'Valeni',
    'Valeni (Ruginesti)': 'Valeni',
    'Valeni (Straoane)': 'Valeni',
    'Viisoara (Paunesti)': 'Viisoara',
    'Viisoara (Vidra)': 'Viisoara',
  },
}
