/* eslint-disable @typescript-eslint/no-throw-literal */
/* eslint-disable func-names */
import type { LocalityMappingData } from '../../models/mapping-data.model'

export default <LocalityMappingData>{
  AB: {
    'Avramesti (Arieseni)': 'Avramesti(Arieseni)',
    'Avramesti (Avram Iancu)': 'Avramesti(Avram Iancu)',
    'Barlesti (Bistra)': 'Barlesti(Bistra)',
    'Barlesti (Mogos)': 'Barlesti(Mogos)',
    'Barlesti (Scarisoara)': 'Barlesti(Scarisoara)',
    'Bobaresti (Sohodol)': 'Bobaresti(Sohodol)',
    'Bobaresti (Vidra)': 'Bobaresti(Vidra)',
    'Bogdanesti (Mogos)': 'Bogdanesti(Mogos)',
    'Bogdanesti (Vidra)': 'Bogdanesti(Vidra)',
    'Botesti (Campeni)': 'Botesti(Campeni)',
    'Botesti (Scarisoara)': 'Botesti(Scarisoara)',
    'Botesti (Zlatna)': 'Botesti(Zlatna)',
    'Butesti (Horea)': 'Butesti(Horea)',
    'Butesti (Mogos)': 'Butesti(Mogos)',
    'Carpinis (Garbova)': 'Carpinis(Garbova)',
    'Carpinis (Rosia Montana)': 'Carpinis(Rosia Montana)',
    'Costesti (Albac)': 'Costesti(Albac)',
    'Costesti (Poiana Vadului)': 'Costesti(Poiana Vadului)',
    'Dealu Frumos (Garda de Sus)': 'Dealu Frumos(Garda de Sus)',
    'Dealu Frumos (Vadu Motilor)': 'Dealu Frumos(Vadu Motilor)',
    'Dumbrava (Ciugud)': 'Dumbrava(Ciugud)',
    'Dumbrava (Sasciori)': 'Dumbrava(Sasciori)',
    'Dumbrava (Unirea)': 'Dumbrava(Unirea)',
    'Dumbrava (Zlatna)': 'Dumbrava(Zlatna)',
    'Dupa Deal (Lupsa)': 'Dupa Deal(Lupsa)',
    'Dupa Deal (Ponor)': 'Dupa Deal(Ponor)',
    Falaud() {
      throw 'Unavailable destination'
    },
    'Floresti (Bucium)': 'Floresti(Bucium)',
    'Floresti (Campeni)': 'Floresti(Campeni)',
    'Floresti (Ramet)': 'Floresti(Ramet)',
    'Floresti (Scarisoara)': 'Floresti(Scarisoara)',
    'Furduiesti (Campeni)': 'Furduiesti(Campeni)',
    'Furduiesti (Sohodol)': 'Furduiesti(Sohodol)',
    'Hanasesti (Garda de Sus)': 'Hanasesti(Garda de Sus)',
    'Hanasesti (Poiana Vadului)': 'Hanasesti(Poiana Vadului)',
    'Hoanca (Sohodol)': 'Hoanca(Sohodol)',
    'Hoanca (Vidra)': 'Hoanca(Vidra)',
    'Incesti (Avram Iancu)': 'Incesti(Avram Iancu)',
    'Incesti (Posaga)': 'Incesti(Posaga)',
    'Izvoarele (Blaj)': 'Izvoarele(Blaj)',
    'Izvoarele (Garda de Sus)': 'Izvoarele(Garda de Sus)',
    'Izvoarele (Livezile)': 'Izvoarele(Livezile)',
    'Laz (Sasciori)': 'Laz(Sasciori)',
    'Laz (Vintu de Jos)': 'Laz(Vintu de Jos)',
    'Lazesti (Scarisoara)': 'Lazesti(Scarisoara)',
    'Lazesti (Vadu Motilor)': 'Lazesti(Vadu Motilor)',
    'Lazuri (Lupsa)': 'Lazuri(Lupsa)',
    'Lazuri (Sohodol)': 'Lazuri(Sohodol)',
    'Lunca (Lupsa)': 'Lunca(Lupsa)',
    'Lunca (Posaga)': 'Lunca(Posaga)',
    'Lunca (Valea Lunga)': 'Lunca(Valea Lunga)',
    'Lunca (Vidra)': 'Lunca(Vidra)',
    'Lunca Larga (Bistra)': 'Lunca Larga(Bistra)',
    'Lunca Larga (Ocolis)': 'Lunca Larga(Ocolis)',
    'Magura (Bucium)': 'Magura(Bucium)',
    'Magura (Galda de Jos)': 'Magura(Galda de Jos)',
    'Matisesti (Ciuruleasa)': 'Matisesti(Ciuruleasa)',
    'Matisesti (Horea)': 'Matisesti(Horea)',
    'Modolesti (Intregalde)': 'Modolesti(intregalde)',
    'Modolesti (Vidra)': 'Modolesti(Vidra)',
    'Moraresti (Ciuruleasa)': 'Moraresti(Ciuruleasa)',
    'Moraresti (Sohodol)': 'Moraresti(Sohodol)',
    Piclisa() {
      throw 'Unavailable destination'
    },
    'Plai (Avram Iancu)': 'Plai(Avram Iancu)',
    'Plai (Garda de Sus)': 'Plai(Garda de Sus)',
    'Poiana (Bistra)': 'Poiana(Bistra)',
    'Poiana (Bucium)': 'Poiana(Bucium)',
    'Poiana (Sohodol)': 'Poiana(Sohodol)',
    'Poieni (Blandiana)': 'Poieni(Blandiana)',
    'Poieni (Bucium)': 'Poieni(Bucium)',
    'Poieni (Vidra)': 'Poieni(Vidra)',
    'Poienita (Arieseni)': 'Poienita(Arieseni)',
    'Poienita (Vintu de Jos)': 'Poienita(Vintu de Jos)',
    Preluca() {
      throw 'Unavailable destination'
    },
    Rametea() {
      throw 'Unavailable destination'
    },
    'Runc (Ocolis)': 'Runc(Ocolis)',
    'Runc (Scarisoara)': 'Runc(Scarisoara)',
    'Runc (Vidra)': 'Runc(Vidra)',
    'Runc (Zlatna)': 'Runc(Zlatna)',
    Saciori() {
      throw 'Unavailable destination'
    },
    'Sohodol (Albac)': 'Sohodol(Albac)',
    Tau: 'Tau Bistra',
    'Tau Bistra': 'Tau',
    'Trifesti (Horea)': 'Trifesti(Horea)',
    'Trifesti (Lupsa)': 'Trifesti(Lupsa)',
    'Valea Mare (Gurahont)': 'Valea Mare(Gurahont)',
    'Valea Poienii (Bucium)': 'Valea Poienii(Bucium)',
    'Valea Poienii (Ramet)': 'Valea Poienii(Ramet)',
    'Valea Sesii (Bucium)': 'Valea sesii(Bucium)',
    'Valea Sesii (Lupsa)': 'Valea sesii(Lupsa)',
    'Valeni (Bucium)': 'Valeni(Bucium)',
    'Valeni (Metes)': 'Valeni(Metes)',
    'Valtori (Vadu Motilor)': 'Valtori(Vadu Motilor)',
    'Valtori (Zlatna)': 'Valtori(Zlatna)',
  },
  AR: {
    'Avram Iancu (Cermei)': 'Avram Iancu(Cermei)',
    'Avram Iancu (Varfurile)': 'Avram Iancu(Varfurile)',
    'Valea Mare (Gurahont)': 'Valea Mare(Gurahont)',
    'Valea Mare (Savarsin)': 'Valea Mare(Savarsin)',
  },
  AG: {
    'Alunisu (Baiculesti)': 'Alunisu(Baiculesti)',
    'Alunisu (Bradulet)': 'Alunisu(Bradulet)',
    'Badesti (Barla)': 'Badesti(Barla)',
    'Badesti (Pietrosani)': 'Badesti(Pietrosani)',
    'Balilesti (Tigveni)': 'Balilesti(Tigveni)',
    'Bratia (Berevoesti)': 'Bratia(Berevoesti)',
    'Bratia (Ciomagesti)': 'Bratia(Ciomagesti)',
    'Brosteni (Aninoasa)': 'Brosteni(Aninoasa)',
    'Brosteni (Costesti)': 'Brosteni(Costesti)',
    'Bunesti (Cotmeana)': 'Bunesti(Cotmeana)',
    'Bunesti (Malureni)': 'Bunesti(Malureni)',
    'Capu Piscului (Godeni)': 'Capu Piscului(Godeni)',
    'Capu Piscului (Merisani)': 'Capu Piscului(Merisani)',
    'Cepari (Poiana Lacului)': 'Cepari(Poiana Lacului)',
    'Chiritesti (Suseni)': 'Chiritesti(Suseni)',
    'Chiritesti (Uda)': 'Chiritesti(Uda)',
    'Chiritesti (Vedea)': 'Chiritesti(Vedea)',
    'Costesti (Cotmeana)': 'Costesti(Cotmeana)',
    'Cotmeana (Stolnici)': 'Cotmeana(Stolnici)',
    'Cotu (Cuca)': 'Cotu(Cuca)',
    'Cotu (Uda)': 'Cotu(Uda)',
    'Dealu Viilor (Mosoaia)': 'Dealu Viilor(Mosoaia)',
    'Dealu Viilor (Poiana Lacului)': 'Dealu Viilor(Poiana Lacului)',
    'Galasesti (Budeasa)': 'Galasesti(Budeasa)',
    'Galasesti (Suseni)': 'Galasesti(Suseni)',
    'Glodu (Calinesti)': 'Glodu(Calinesti)',
    'Glodu (Leordeni)': 'Glodu(Leordeni)',
    'Golesti (Balilesti)': 'Golesti(Balilesti)',
    'Golesti (Stefanesti)': 'Golesti(stefanesti)',
    'Gruiu (Cateasca)': 'Gruiu(Cateasca)',
    'Gruiu (Nucsoara)': 'Gruiu(Nucsoara)',
    'Lazaresti (Mosoaia)': 'Lazaresti(Mosoaia)',
    'Lazaresti (Schitu Golesti)': 'Lazaresti(Schitu Golesti)',
    'Malu (Barla)': 'Malu(Barla)',
    'Malu (Godeni)': 'Malu(Godeni)',
    'Mioarele (Cicanesti)': 'Mioarele(Cicanesti)',
    'Pauleasca (Malureni)': 'Pauleasca(Malureni)',
    'Pauleasca (Micesti)': 'Pauleasca(Micesti)',
    'Piatra (Bradulet)': 'Piatra(Bradulet)',
    'Piatra (Ciofrangeni)': 'Piatra(Ciofrangeni)',
    'Piatra (Stoenesti)': 'Piatra(Stoenesti)',
    'Poienari (Corbeni)': 'Poienari(Corbeni)',
    'Poienari (Poienarii de Arges)': 'Poienari(Poienarii de Arges)',
    'Poienari (Poienarii de Muscel)': 'Poienari(Poienarii de Muscel)',
    'Popesti (Cocu)': 'Popesti(Cocu)',
    'Popesti (Sapata)': 'Popesti(Sapata)',
    'Purcareni (Micesti)': 'Purcareni(Micesti)',
    'Purcareni (Popesti)': 'Purcareni(Popesti)',
    'Recea (Cateasca)': 'Recea(Cateasca)',
    'Rudeni (Mihaesti)': 'Rudeni(Mihaesti)',
    'Rudeni (Suici)': 'Rudeni(suici)',
    'Serbanesti (Poienarii de Muscel)': 'serbanesti(Poienarii de Muscel)',
    'Serbanesti (Rociu)': 'serbanesti(Rociu)',
    'Slobozia (Popesti)': 'Slobozia(Popesti)',
    'Slobozia (Stoenesti)': 'Slobozia(Stoenesti)',
    'Stefanesti (Suseni)': 'stefanesti(Suseni)',
    'Strambeni (Caldararu)': 'Strambeni(Caldararu)',
    'Strambeni (Suseni)': 'Strambeni(Suseni)',
    'Suseni (Bogati)': 'Suseni(Bogati)',
    'Tigveni (Ratesti)': 'Tigveni(Ratesti)',
    'Ungureni (Bradulet)': 'Ungureni(Bradulet)',
    'Ungureni (Valea Iasului)': 'Ungureni(Valea Iasului)',
    'Valea Popii (Mihaesti)': 'Valea Popii(Mihaesti)',
    'Valea Popii (Priboieni)': 'Valea Popii(Priboieni)',
    'Vladesti (Tigveni)': 'Vladesti(Tigveni)',
    'Zamfiresti (Cepari)': 'Zamfiresti(Cepari)',
    'Zamfiresti (Cotmeana)': 'Zamfiresti(Cotmeana)',
  },
  BC: {
    'Balanesti (Dealu Morii)': 'Balanesti(Dealu Morii)',
    'Balanesti (Podu Turcului)': 'Balanesti(Podu Turcului)',
    'Bogdanesti (Scorteni)': 'Bogdanesti(Scorteni)',
    'Bogdanesti (Traian)': 'Bogdanesti(Traian)',
    'Brad (Beresti-Bistrita)': 'Brad(Beresti-Bistrita)',
    'Brad (Filipeni)': 'Brad(Filipeni)',
    'Brad (Negri)': 'Brad(Negri)',
    'Buda (Berzunti)': 'Buda(Berzunti)',
    'Buda (Blagesti)': 'Buda(Blagesti)',
    'Buda (Rachitoasa)': 'Buda(Rachitoasa)',
    'Cucuieti (Dofteana)': 'Cucuieti(Dofteana)',
    'Cucuieti (Solont)': 'Cucuieti(Solont)',
    'Dorneni (Plopana)': 'Dorneni(Plopana)',
    'Dorneni (Vultureni)': 'Dorneni(Vultureni)',
    'Dragesti (Damienesti)': 'Dragesti(Damienesti)',
    'Dragesti (Tatarasti)': 'Dragesti(Tatarasti)',
    'Dumbrava (Gura Vaii)': 'Dumbrava(Gura Vaii)',
    'Dumbrava (Itesti)': 'Dumbrava - Itesti',
    'Dumbrava (Rachitoasa)': 'Dumbrava(Rachitoasa)',
    'Fantanele (Hemeius)': 'Fantanele(Hemeius)',
    'Fantanele (Motoseni)': 'Fantanele(Motoseni)',
    'Filipesti (Bogdanesti)': 'Filipesti(Bogdanesti)',
    'Floresti (Caiuti)': 'Floresti(Caiuti)',
    'Floresti (Huruiesti)': 'Floresti(Huruiesti)',
    'Floresti (Scorteni)': 'Floresti(Scorteni)',
    'Galbeni (Filipesti)': 'Galbeni(Filipesti)',
    'Galbeni (Nicolae Balcescu)': 'Galbeni(Nicolae Balcescu)',
    'Gura Vaii (Racova)': 'Gura Vaii(Racova)',
    'Haghiac (Dofteana)': 'Haghiac(Dofteana)',
    'Haghiac (Rachitoasa)': 'Haghiac(Rachitoasa)',
    'Marginea (Buhusi)': 'Marginea(Buhusi)',
    'Marginea (Oituz)': 'Marginea(Oituz)',
    'Padureni (Beresti-Bistrita)': 'Padureni(Beresti-Bistrita)',
    'Padureni (Damienesti)': 'Padureni(Damienesti)',
    'Padureni (Filipeni)': 'Padureni(Filipeni)',
    'Padureni (Izvoru Berheciului)': 'Padureni(Izvoru Berheciului)',
    'Padureni (Margineni)': 'Padureni(Margineni)',
    'Pancesti (Sascut)': function () {
      throw 'Unavailable destination'
    },
    'Plopu (Darmanesti)': 'Plopu(Darmanesti)',
    'Plopu (Podu Turcului)': 'Plopu(Podu Turcului)',
    'Poiana (Colonesti)': 'Poiana(Colonesti)',
    'Poiana (Livezi)': 'Poiana(Livezi)',
    'Poiana (Margineni)': 'Poiana(Margineni)',
    'Poiana (Motoseni)': 'Poiana(Motoseni)',
    'Poiana (Negri)': 'Poiana(Negri)',
    'Poieni (Parincea)': 'Poieni(Parincea)',
    'Poieni (Rosiori)': 'Poieni(Rosiori)',
    'Poieni (Targu Ocna)': 'Poieni(Targu Ocna)',
    'Prajesti (Magiresti)': 'Prajesti(Magiresti)',
    'Sarata (Nicolae Balcescu)': 'Sarata',
    'Sarata (Solont)': 'Sarata(Solont)',
    'Satu Nou (Colonesti)': 'Satu Nou(Colonesti)',
    'Satu Nou (Lipova)': 'Satu Nou(Lipova)',
    'Satu Nou (Oncesti)': 'Satu Nou(Oncesti)',
    'Satu Nou (Pargaresti)': 'Satu Nou(Pargaresti)',
    'Satu Nou (Parincea)': 'Satu Nou(Parincea)',
    'Satu Nou (Urechesti)': 'Satu Nou(Urechesti)',
    'Schineni (Sascut)': 'Schineni(Sascut)',
    'Schineni (Saucesti)': 'Schineni(Saucesti)',
    'Siretu (Letea Veche)': 'Siretu(Letea Veche)',
    'Siretu (Saucesti)': 'Siretu(Saucesti)',
    'Slobozia (Filipeni)': 'Slobozia(Filipeni)',
    'Slobozia (Onesti)': 'Slobozia(Onesti)',
    'Slobozia (Stanisesti)': 'Slobozia(Stanisesti)',
    'Slobozia (Urechesti)': 'Slobozia(Urechesti)',
    'Ungureni (Tatarasti)': 'Ungureni(Tatarasti)',
    'Valcele (Corbasca)': 'Valcele(Corbasca)',
    'Valcele (Targu Ocna)': 'Valcele(Targu Ocna)',
    'Valea Mare (Colonesti)': 'Valea Mare(Colonesti)',
    'Valea Mare (Rosiori)': 'Valea Mare(Rosiori)',
    'Valea Mica (Cleja)': 'Valea Mica(Cleja)',
    'Valea Mica (Rosiori)': 'Valea Mica(Rosiori)',
    'Valea Seaca (Nicolae Balcescu)': 'Valea Seaca(Nicolae Balcescu)',
    'Valeni (Parincea)': 'Valeni(Parincea)',
    'Valeni (Secuieni)': 'Valeni(Secuieni)',
    'Valeni (Stanisesti)': 'Valeni(Stanisesti)',
    'Viisoara (Stefan cel Mare)': 'Viisoara(stefan cel Mare)',
    'Viisoara (Targu Trotus)': 'Viisoara(Targu Trotus)',
    'Zapodia (Colonesti)': 'Zapodia(Colonesti)',
    'Zapodia (Traian)': 'Zapodia(Traian)',
  },
  BH: {
    'Almasu Mic (Balc)': 'Almasu Mic(Balc)',
    'Almasu Mic (Sarbi)': 'Almasu Mic(Sarbi)',
    Balc() {
      throw 'Unavailable destination'
    },
    'Brusturi (Finis)': 'Brusturi(Finis)',
    'Gurbesti (Cabesti)': 'Gurbesti(Cabesti)',
    'Gurbesti (Spinus)': 'Gurbesti(Spinus)',
    'Josani (Cabesti)': 'Josani(Cabesti)',
    'Josani (Magesti)': 'Josani(Magesti)',
    'Poiana (Cristioru de Jos)': 'Poiana(Tauteu)',
    'Poiana (Tauteu)': 'Poiana(Cristioru de Jos)',
    'Voivozi (Popesti)': 'Voivozi(Popesti)',
    'Voivozi (Simian)': 'Voivozi(simian)',
  },
  BN: {},
  BT: {
    'Baranca (Cristinesti)': 'Baranca(Cristinesti)',
    'Baranca (Hudesti)': 'Baranca(Hudesti)',
    'Calinesti (Bucecea)': 'Calinesti(Bucecea)',
    'Calinesti (Candesti)': 'Calinesti(Candesti)',
    'Calinesti (Mihaileni)': function () {
      throw 'Unavailable destination'
    },
    'Dragalina (Cristinesti)': 'Dragalina(Cristinesti)',
    'Dragalina (Hlipiceni)': 'Dragalina(Hlipiceni)',
    'Durnesti (Santa Mare)': 'Durnesti(Santa Mare)',
    'Durnesti (Ungureni)': 'Durnesti(Ungureni)',
    'Ionaseni (Trusesti)': 'Ionaseni(Trusesti)',
    'Ionaseni (Varfu Campului)': 'Ionaseni(Varfu Campului)',
    'Lunca (Varfu Campului)': 'Lunca(Varfu Campului)',
    'Mandresti (Ungureni)': 'Mandresti(Ungureni)',
    'Mandresti (Vladeni)': 'Mandresti(Vladeni)',
    'Mihai Eminescu (Gorbanesti)': 'Mihai Eminescu(Gorbanesti)',
    'Mitoc (Leorda)': 'Mitoc(Leorda)',
    'Nicolae Balcescu (Cotusca)': 'Nicolae Balcescu(Cotusca)',
    'Nicolae Balcescu (Flamanzi)': 'Nicolae Balcescu(Flamanzi)',
    'Padureni (Cosula)': 'Padureni(Cosula)',
    'Padureni (Sendriceni)': 'Padureni(sendriceni)',
    'Poiana (Braesti)': 'Poiana(Braesti)',
    'Poiana (Cristinesti)': 'Poiana(Cristinesti)',
    'Poiana (Flamanzi)': 'Poiana(Flamanzi)',
    'Poiana (Vorona)': 'Poiana(Vorona)',
    'Popeni (Braesti)': 'Popeni(Braesti)',
    'Popeni (George Enescu)': 'Popeni(George Enescu)',
    'Rediu (Radauti-Prut)': 'Rediu(Radauti-Prut)',
    'Rediu (Rauseni)': 'Rediu(Rauseni)',
    Sarata() {
      throw 'Unavailable destination'
    },
    'Slobozia (Broscauti)': 'Slobozia(Broscauti)',
    'Slobozia (Cordareni)': 'Slobozia(Cordareni)',
    'Slobozia (Paltinis)': 'Slobozia(Paltinis)',
    'Stanca (George Enescu)': 'Stanca(George Enescu)',
    'Stanca (Stefanesti)': 'Stanca(stefanesti)',
    'Tudor Vladimirescu (Albesti)': 'Tudor Vladimirescu(Albesti)',
    'Tudor Vladimirescu (Avrameni)': 'Tudor Vladimirescu(Avrameni)',
    'Victoria (Hlipiceni)': 'Victoria(Hlipiceni)',
    'Victoria (Stauceni)': 'Victoria(Stauceni)',
    Viisoara: 'Viisoara Mica',
    'Viisoara Mica': 'Viisoara',
    'Vladeni (Corlateni)': 'Vladeni(Corlateni)',
  },
  BR: {
    'Cuza Voda (Salcia Tudor)': 'Cuza Voda(Salcia Tudor)',
    'Cuza Voda (Stancuta)': 'Cuza Voda(Stancuta)',
    'Mihail Kogalniceanu (Ramnicelu)': 'Mihail Kogalniceanu(Ramnicelu)',
    'Mihail Kogalniceanu (Sutesti)': 'Mihail Kogalniceanu(sutesti)',
  },
  BV: {
    Bradet() {
      throw 'Unavailable destination'
    },
    'Feldioara (Ucea)': 'Feldioara(Ucea)',
  },
  B: {},
  BZ: {
    'Corbu (Catina)': 'Corbu(Catina)',
    'Corbu (Glodeanu-Silistea)': 'Corbu(Glodeanu-Silistea)',
    'Fantanele (Margaritesti)': 'Fantanele(Margaritesti)',
    'Fantanele (Naeni)': 'Fantanele(Naeni)',
    'Izvoru (Cozieni)': 'Izvoru(Cozieni)',
    'Izvoru (Tisau)': 'Izvoru(Tisau)',
    'Izvoru Dulce (Beceni)': 'Izvoru Dulce(Beceni)',
    'Izvoru Dulce (Merei)': 'Izvoru Dulce(Merei)',
    'Lunca (Amaru)': 'Lunca(Amaru)',
    'Lunca (C.A. Rosetti)': 'Lunca(C.A. Rosetti)',
    'Lunca (Patarlagele)': 'Lunca(Patarlagele)',
    'Lunca (Puiesti)': 'Lunca(Puiesti)',
    Muscel() {
      throw 'Unavailable destination'
    },
    'Plesesti (Berca)': 'Plesesti(Berca)',
    'Plesesti (Podgoria)': 'Plesesti(Podgoria)',
    'Posta (Cilibia)': 'Posta(Cilibia)',
    'Posta (Topliceni)': 'Posta(Topliceni)',
    'Satu Nou (Glodeanu-Silistea)': 'Satu Nou(Glodeanu-Silistea)',
    'Satu Nou (Mihailesti)': 'Satu Nou(Mihailesti)',
    'Suditi (Gheraseni)': 'Suditi(Gheraseni)',
    'Suditi (Posta Calnau)': 'Suditi(Posta Calnau)',
    'Trestioara (Chiliile)': 'Trestioara(Chiliile)',
    'Trestioara (Manzalesti)': 'Trestioara(Manzalesti)',
  },
  CL: {
    'Chirnogi (Ulmu)': 'Chirnogi(Ulmu)',
    'Dorobantu (Plataresti)': 'Dorobantu(Plataresti)',
    'Nicolae Balcescu (Alexandru Odobescu)':
      'Nicolae Balcescu(Alexandru Odobescu)',
  },
  CS: {
    'Cuptoare (Cornea)': 'Cuptoare(Cornea)',
    'Cuptoare (Resita)': 'Cuptoare(Resita)',
    'Macoviste (Ciuchici)': 'Macoviste(Ciuchici)',
    'Macoviste (Cornea)': 'Macoviste(Cornea)',
    'Prislop (Cornereva)': 'Prislop(Cornereva)',
    'Prislop (Dalboset)': 'Prislop(Dalboset)',
  },
  CJ: {
    'Balcesti (Belis)': 'Balcesti(Belis)',
    'Balcesti (Capusu Mare)': 'Balcesti(Capusu Mare)',
    'Cornesti (Garbau)': 'Cornesti(Garbau)',
    'Cornesti (Mihai Viteazu)': 'Cornesti(Mihai Viteazu)',
    'Hasdate (Gherla)': 'Hasdate(Gherla)',
    'Hasdate (Savadisla)': 'Hasdate(Savadisla)',
    'Livada (Iclod)': 'Livada(Iclod)',
    'Livada (Petrestii de Jos)': 'Livada(Petrestii de Jos)',
    'Padureni (Chinteni)': 'Padureni(Chinteni)',
    'Padureni (Ciurila)': 'Padureni(Ciurila)',
    'Padurenii (Mintiu Gherlii)': 'Padurenii(Mintiu Gherlii)',
    'Padurenii (Tritenii de Jos)': 'Padurenii(Tritenii de Jos)',
    Risca() {
      throw 'Unavailable destination'
    },
    'Sanmartin (Chinteni)': 'Sanmartin(Chinteni)',
    'Straja (Capusu Mare)': 'Straja(Cojocna)',
    'Straja (Cojocna)': 'Straja(Capusu Mare)',
    'Valeni (Caianu)': 'Valeni(Caianu)',
    'Valeni (Calatele)': 'Valeni(Calatele)',
  },
  CT: {
    Basarabi() {
      throw 'Unavailable destination'
    },
    'Satu Nou (Mircea Voda)': 'Satu Nou(Mircea Voda)',
    'Satu Nou (Oltina)': 'Satu Nou(Oltina)',
  },
  CV: {},
  DB: {
    'Brosteni (Bezdead)': 'Brosteni(Bezdead)',
    'Brosteni (Produlesti)': 'Brosteni(Produlesti)',
    'Brosteni (Visina)': 'Brosteni(Visina)',
    'Calugareni (Cobia)': 'Calugareni(Cobia)',
    'Calugareni (Contesti)': 'Calugareni(Contesti)',
    'Catunu (Cornesti)': 'Catunu(Cornesti)',
    'Catunu (Salcioara)': 'Catunu(Salcioara)',
    'Glodeni (Pucioasa)': 'Glodeni(Pucioasa)',
    'Izvoru (Valea Lunga)': 'Izvoru(Valea Lunga)',
    'Izvoru (Visina)': 'Izvoru(Visina)',
    'Livezile (Glodeni)': 'Livezile(Glodeni)',
    'Livezile (Valea Mare)': 'Livezile(Valea Mare)',
    'Lunca (Moroeni)': 'Lunca(Moroeni)',
    'Lunca (Voinesti)': 'Lunca(Voinesti)',
    'Magura (Bezdead)': 'Magura(Bezdead)',
    'Magura (Hulubesti)': 'Magura(Hulubesti)',
    Manastirea() {
      throw 'Unavailable destination'
    },
    'Mereni (Contesti)': 'Mereni(Contesti)',
    'Mereni (Titu)': 'Mereni(Titu)',
    'Movila (Niculesti)': 'Movila(Niculesti)',
    'Movila (Salcioara)': 'Movila(Salcioara)',
    'Olteni (Lucieni)': 'Olteni(Lucieni)',
    'Olteni (Uliesti)': 'Olteni(Uliesti)',
    'Petresti (Corbii Mari)': 'Petresti(Corbii Mari)',
    'Priboiu (Branesti)': 'Priboiu(Branesti)',
    'Priboiu (Tatarani)': 'Priboiu(Tatarani)',
    'Pucheni (Moroeni)': 'Pucheni(Moroeni)',
    'Salcioara (Matasaru)': 'Salcioara(Matasaru)',
    'Silistea (Raciu)': 'Silistea(Raciu)',
    'Silistea (Runcu)': 'Silistea(Runcu)',
    'Ungureni (Butimanu)': 'Ungureni(Butimanu)',
    'Ungureni (Corbii Mari)': 'Ungureni(Corbii Mari)',
    'Ungureni (Cornesti)': 'Ungureni(Cornesti)',
    'Ungureni (Dragomiresti)': 'Ungureni(Dragomiresti)',
    Valea() {
      throw 'Unavailable destination'
    },
    'Valea Mare (Candesti)': 'Valea Mare(Candesti)',
    'Valea Mare (Valea Lunga)': 'Valea Mare(Valea Lunga)',
  },
  DJ: {
    'Bechet (Orodel)': 'Bechet(Orodel)',
    'Braniste (Daneti)': 'Braniste(Daneti)',
    'Braniste (Filiasi)': 'Braniste(Filiasi)',
    'Braniste (Podari)': 'Braniste(Podari)',
    Cernele() {
      throw 'Unavailable destination'
    },
    'Cetatuia (Cioroiasi)': 'Cetatuia(Cioroiasi)',
    'Cetatuia (Vela)': 'Cetatuia(Vela)',
    'Fantanele (Radovan)': 'Fantanele(Radovan)',
    'Fantanele (Teslui)': 'Fantanele(Teslui)',
    Rovine() {
      throw 'Unavailable destination'
    },
    'Salcuta (Calopar)': 'Salcuta(Calopar)',
  },
  GL: {
    'Branistea (Nicoresti)': 'Branistea(Nicoresti)',
    'Liesti (Priponesti)': 'Liesti(Priponesti)',
    'Movileni (Sendreni)': 'Movileni(sendreni)',
    'Umbraresti (Targu Bujor)': 'Umbraresti(Targu Bujor)',
  },
  GR: {
    'Cascioarele (Gaiseni)': 'Cascioarele(Gaiseni)',
    'Cascioarele (Ulmi)': 'Cascioarele(Ulmi)',
    Isvoarele: 'Izvoarele',
    Izvoarele() {
      throw 'Unavailable destination'
    },
    'Izvoru (Gogosari)': 'Izvoru(Gogosari)',
    'Izvoru (Vanatorii Mici)': 'Izvoru(Vanatorii Mici)',
    'Sfantu Gheorghe (Baneasa)': 'Sfantu Gheorghe(Baneasa)',
    'Sfantu Gheorghe (Crevedia Mare)': 'Sfantu Gheorghe(Crevedia Mare)',
    'Stoenesti (Floresti-Stoenesti)': 'Stoenesti(Floresti-Stoenesti)',
  },
  GJ: {
    Lainici() {
      throw 'Unavailable destination'
    },
    Valea() {
      throw 'Unavailable destination'
    },
    Vart() {
      throw 'Unavailable destination'
    },
  },
  HR: {
    'Bucin (Joseni)': 'Bucin(Joseni)',
    'Bucin (Praid)': 'Bucin(Praid)',
    'Fagetel (Frumoasa)': 'Fagetel(Frumoasa)',
    'Fagetel (Remetea)': 'Fagetel(Remetea)',
    'Garciu (Racu)': function () {
      throw 'Unavailable destination'
    },
    'Miercurea-Ciuc': 'Miercurea Ciuc',
    'Mihaileni (Simonesti)': 'Mihaileni(simonesti)',
    'Nicolesti (Frumoasa)': 'Nicolesti(Frumoasa)',
    'Nicolesti (Ulies)': 'Nicolesti(Ulies)',
    'Satu Nou (Ocland)': 'Satu Nou(Ocland)',
    'Satu Nou (Racu)': 'Satu Nou(Racu)',
  },
  HD: {
    'Alun (Bosorod)': 'Alun(Bosorod)',
    'Alun (Bunila)': 'Alun(Bunila)',
    'Lunca (Baia de Cris)': 'Lunca(Baia de Cris)',
    'Lunca (Baita)': 'Lunca(Baita)',
    'Merisor (Banita)': 'Merisor(Banita)',
    'Merisor (Bucuresci)': 'Merisor(Bucuresci)',
    'Mesteacan (Brad)': 'Mesteacan(Brad)',
    'Mesteacan (Rachitova)': 'Mesteacan(Rachitova)',
    'Pestera (Baita)': 'Pestera(Baita)',
    'Pestera (Petrosani)': 'Pestera(Petrosani)',
    'Pestera (Salasu de Sus)': 'Pestera(Salasu de Sus)',
    'Poieni (Beriu)': 'Poieni(Beriu)',
    'Poieni (Densus)': 'Poieni(Densus)',
    'Prihodiste (Bosorod)': 'Prihodiste(Bosorod)',
    'Prihodiste (Vata de Jos)': 'Prihodiste(Vata de Jos)',
    'Radulesti (Stancesti)': 'Radulesti',
    'Rovina (Branisca)': 'Rovina(Branisca)',
    'Rovina (Bucuresci)': 'Rovina(Bucuresci)',
    'Sibisel (Beriu)': 'Sibisel(Beriu)',
    'Sibisel (Rau de Mori)': 'Sibisel(Rau de Mori)',
    'Valeni (Baia de Cris)': 'Valeni(Baia de Cris)',
    'Valeni (Geoagiu)': 'Valeni(Geoagiu)',
    'Valisoara (Balsa)': 'Valisoara(Balsa)',
  },
  IL: {},
  IS: {
    'Baiceni (Cucuteni)': 'Baiceni(Cucuteni)',
    'Baiceni (Todiresti)': 'Baiceni(Todiresti)',
    'Boureni (Bals)': 'Boureni(Bals)',
    'Boureni (Motca)': 'Boureni(Motca)',
    'Buda (Braesti)': 'Buda(Braesti)',
    'Buda (Lespezi)': 'Buda(Lespezi)',
    'Cozmesti (Stolniceni-Prajescu)': 'Cozmesti(Stolniceni-Prajescu)',
    'Cristesti (Braesti)': 'Cristesti(Braesti)',
    'Cristesti (Holboca)': 'Cristesti(Holboca)',
    'Crivesti (Strunga)': 'Crivesti(Strunga)',
    'Crivesti (Vanatori)': 'Crivesti(Vanatori)',
    'Cucuteni (Letcani)': 'Cucuteni(Letcani)',
    'Cuza Voda (Ipatele)': 'Cuza Voda(Ipatele)',
    'Cuza Voda (Popricani)': 'Cuza Voda(Popricani)',
    'Deleni (Ciortesti)': 'Deleni(Ciortesti)',
    'Dumbrava (Ciurea)': 'Dumbrava(Ciurea)',
    'Dumbrava (Lespezi)': 'Dumbrava(Lespezi)',
    Fantanele: 'Fantanele(Andrieseni)',
    'Fantanele (Andrieseni)': 'Fantanele',
    'Horlesti (Rediu)': 'Horlesti(Rediu)',
    'Iepureni (Andrieseni)': 'Iepureni(Andrieseni)',
    'Iepureni (Movileni)': 'Iepureni(Movileni)',
    'Lunca (Grajduri)': 'Lunca(Grajduri)',
    'Lunca (Pascani)': 'Lunca(Pascani)',
    'Lungani (Voinesti)': 'Lungani(Voinesti)',
    'Movileni (Helesteni)': 'Movileni(Helesteni)',
    'Osoi (Comarna)': 'Osoi(Comarna)',
    'Osoi (Sinesti)': 'Osoi(Sinesti)',
    'Padureni (Grajduri)': 'Padureni(Grajduri)',
    'Padureni (Popesti)': 'Padureni(Popesti)',
    'Poiana (Deleni)': 'Poiana(Deleni)',
    'Poiana (Schitu Duca)': 'Poiana(Schitu Duca)',
    'Rediu (Braesti)': 'Rediu(Braesti)',
    'Rediu (Ruginoasa)': 'Rediu(Ruginoasa)',
    'Rediu (Scanteia)': 'Rediu(Scanteia)',
    'Satu Nou': function () {
      throw 'Unavailable destination'
    },
    'Satu Nou (Belcesti)': 'Satu Nou(Belcesti)',
    'Satu Nou (Scheia)': 'Satu Nou(scheia)',
    'Satu Nou (Siretel)': 'Satu Nou(Siretel)',
    Scheia: 'Scheia(A.I. Cuza)',
    'Scoposeni (Gorban)': 'Scoposeni(Gorban)',
    'Scoposeni (Horlesti)': 'Scoposeni(Horlesti)',
    'Slobozia (Ciurea)': 'Slobozia(Ciurea)',
    'Slobozia (Deleni)': 'Slobozia(Deleni)',
    'Slobozia (Schitu Duca)': 'Slobozia(Schitu Duca)',
    'Slobozia (Siretel)': 'Slobozia(Siretel)',
    'Slobozia (Voinesti)': 'Slobozia(Voinesti)',
    'Stanca (Comarna)': 'Stanca(Comarna)',
    'Stanca (Victoria)': 'Stanca(Victoria)',
    'Tansa (Belcesti)': 'Tansa(Belcesti)',
    'Vanatori (Popricani)': 'Vanatori(Popricani)',
  },
  IF: {
    'Pipera (Voluntari)': function () {
      throw 'Unavailable destination'
    },
  },
  MM: {
    'Sarbi (Budesti)': 'Sarbi(Budesti)',
    'Sarbi (Farcasa)': 'Sarbi(Farcasa)',
  },
  MH: {
    'Baltanele (Greci)': 'Baltanele(Greci)',
    'Baltanele (Prunisor)': 'Baltanele(Prunisor)',
    'Godeanu (Obarsia-Closani)': 'Godeanu(Obarsia-Closani)',
    'Sipotu (Ponoarele)': 'sipotu(Ponoarele)',
    'Sipotu (Poroina Mare)': 'sipotu(Poroina Mare)',
    'Susita (Breznita-Ocol)': 'susita(Breznita-Ocol)',
    'Susita (Grozesti)': 'susita(Grozesti)',
    'Valea Ursului (Ponoarele)': 'Valea Ursului(Ponoarele)',
    'Valea Ursului (Tamna)': 'Valea Ursului(Tamna)',
  },
  MS: {
    Ciba() {
      throw 'Unavailable destination'
    },
    'Cornesti (Adamus)': 'Cornesti(Adamus)',
    'Cornesti (Craciunesti)': 'Cornesti(Craciunesti)',
    Craiesti: 'Craiesti(Adamus)',
    'Craiesti (Adamus)': 'Craiesti',
    'Daia (Apold)': 'Daia(Apold)',
    'Daia (Bahnea)': 'Daia(Bahnea)',
    'Deleni (Ideciu de Jos)': 'Deleni(Ideciu de Jos)',
    'Deleni (Pogaceaua)': 'Deleni(Pogaceaua)',
    'Dupa Deal (Cuci)': 'Dupa Deal(Cuci)',
    'Dupa Deal (Iclanzel)': 'Dupa Deal(Iclanzel)',
    'Fanate (Band)': 'Fanate(Band)',
    'Fanate (Faragau)': 'Fanate(Faragau)',
    'Fanate (Iclanzel)': 'Fanate(Iclanzel)',
    'Fanate (Taureni)': 'Fanate(Taureni)',
    'Larga (Gurghiu)': 'Larga(Gurghiu)',
    'Larga (Sarmasu)': 'Larga(Sarmasu)',
    'Parau Crucii (Pogaceaua)': 'Parau Crucii(Pogaceaua)',
    'Parau Crucii (Raciu)': 'Parau Crucii(Raciu)',
    'Satu Nou (Gheorghe Doja)': 'Satu Nou(Gheorghe Doja)',
    'Satu Nou (Sanpetru de Campie)': 'Satu Nou(Sanpetru de Campie)',
    'Seleus (Danes)': 'Seleus(Danes)',
    'Seleus (Zagar)': 'Seleus(Zagar)',
    'Valea Sanpetrului (Grebenisu de Campie)':
      'Valea Sanpetrului(Grebenisu de Campie)',
    'Valea Sanpetrului (Pogaceaua)': 'Valea Sanpetrului(Pogaceaua)',
  },
  NT: {
    'Balusesti (Dochia)': 'Balusesti(Dochia)',
    'Balusesti (Icusesti)': 'Balusesti(Icusesti)',
    Botesti() {
      throw 'Unavailable destination'
    },
    'Botesti (Girov)': 'Botesti(Girov)',
    'Brusturi-Draganesti': function () {
      throw 'Unavailable destination'
    },
    'Izvoare (Bahna)': 'Izvoare(Bahna)',
    'Izvoare (Dumbrava Rosie)': 'Izvoare(Dumbrava Rosie)',
    'Lunca (Borca)': 'Lunca(Borca)',
    'Lunca (Oniceni)': 'Lunca(Oniceni)',
    'Lunca (Vanatori-Neamt)': 'Lunca(Vanatori-Neamt)',
    'Mastacan (Borlesti)': 'Mastacan(Borlesti)',
    'Mastacan (Dragomiresti)': 'Mastacan(Dragomiresti)',
    'Negresti (Bara)': 'Negresti(Bara)',
    'Poiana (Brusturi)': 'Poiana(Brusturi)',
    'Poiana (Dulcesti)': 'Poiana(Dulcesti)',
    'Poiana (Grinties)': 'Poiana(Grinties)',
    'Poiana (Negresti)': 'Poiana(Negresti)',
    'Poiana (Pangarati)': 'Poiana(Pangarati)',
    'Popesti (Farcasa)': 'Popesti(Farcasa)',
    'Popesti (Girov)': 'Popesti(Girov)',
    'Rediu (Bara)': 'Rediu(Bara)',
    'Ruseni (Borlesti)': 'Ruseni(Borlesti)',
    'Ruseni (Poiana Teiului)': 'Ruseni(Poiana Teiului)',
    'Savinesti (Poiana Teiului)': 'Savinesti(Poiana Teiului)',
    'Slobozia (Boghicea)': 'Slobozia(Boghicea)',
    'Slobozia (Roznov)': 'Slobozia(Roznov)',
    'Soci (Borca)': 'Soci(Borca)',
    'Soci (Stefan cel Mare)': 'Soci(stefan cel Mare)',
    'Stejaru (Farcasa)': 'Stejaru(Farcasa)',
    'Stejaru (Ion Creanga)': 'Stejaru(Ion Creanga)',
    'Stejaru (Pangarati)': 'Stejaru(Pangarati)',
    'Traian (Sabaoani)': 'Traian(Sabaoani)',
    'Traian (Zanesti)': 'Traian(Zanesti)',
    'Vadurele (Alexandru cel Bun)': 'Vadurele(Alexandru cel Bun)',
    'Vadurele (Candesti)': 'Vadurele(Candesti)',
    Valeni: 'Valeni(Botesti)',
    'Valeni (Piatra-Neamt)': 'Valeni(Piatra-Neamt)',
  },
  OT: {
    'Barasti (Colonesti)': 'Barasti(Colonesti)',
    'Barasti (Morunglav)': 'Barasti(Morunglav)',
    Barza() {
      throw 'Unavailable destination'
    },
    'Corbu (Teslui)': 'Corbu(Teslui)',
    'Curtisoara (Dobretu)': 'Curtisoara(Dobretu)',
    'Greci (Osica de Sus)': 'Greci(Osica de Sus)',
    'Greci (Schitu)': 'Greci(Schitu)',
    'Magura (Perieti)': 'Magura(Perieti)',
    'Magura (Tatulesti)': 'Magura(Tatulesti)',
    'Maruntei (Colonesti)': 'Maruntei(Colonesti)',
    'Popesti (Barasti)': 'Popesti(Barasti)',
    'Popesti (Valeni)': 'Popesti(Valeni)',
    'Satu Nou (Gradinari)': 'Satu Nou(Gradinari)',
    'Satu Nou (Gura Padinii)': 'Satu Nou(Gura Padinii)',
    'Seaca (Poboru)': 'Seaca(Poboru)',
    'Stanuleasa (Samburesti)': 'Stanuleasa(Samburesti)',
    'Stanuleasa (Vitomiresti)': 'Stanuleasa(Vitomiresti)',
    'Tonesti (Leleasca)': 'Tonesti(Leleasca)',
    'Tonesti (Samburesti)': 'Tonesti(Samburesti)',
    'Valeni (Brancoveni)': 'Valeni(Brancoveni)',
  },
  PH: {
    'Buda (Aricestii Rahtivani)': 'Buda(Aricestii Rahtivani)',
    'Buda (Rafov)': 'Buda(Rafov)',
    'Catunu (Berceni)': 'Catunu(Berceni)',
    'Catunu (Drajna)': 'Catunu(Drajna)',
    'Cornu de Jos (Cornu)': 'Cornu de Jos(Cornu)',
    'Cornu de Jos (Draganesti)': 'Cornu de Jos(Draganesti)',
    'Cornu de Sus (Cornu)': 'Cornu de Sus(Cornu)',
    'Cornu de Sus (Dumbrava)': 'Cornu de Sus(Dumbrava)',
    'Fanari (Gorgota)': 'Fanari(Gorgota)',
    'Fanari (Olari)': 'Fanari(Olari)',
    'Nucet (Chiojdeanca)': 'Nucet(Chiojdeanca)',
    'Nucet (Gornet)': 'Nucet(Gornet)',
    'Persunari (Cocorastii Colt)': 'Persunari(Cocorastii Colt)',
    'Persunari (Gura Vadului)': 'Persunari(Gura Vadului)',
    'Piatra (Cocorastii Colt)': 'Piatra(Manesti)',
    'Piatra (Drajna)': 'Piatra(Drajna)',
    'Piatra (Provita de Jos)': 'Piatra(Provita de Jos)',
    'Plaiu (Provita de Sus)': 'Plaiu(Provita de Sus)',
    'Plaiu (Talea)': 'Plaiu(Talea)',
    'Plopeni (Dumbravesti)': 'Plopeni(Dumbravesti)',
    'Popesti (Brazi)': 'Popesti(Brazi)',
    'Popesti (Podenii Noi)': 'Popesti(Podenii Noi)',
    'Satu Nou (Baba Ana)': 'Satu Nou(Baba Ana)',
    'Satu Nou (Lipanesti)': 'Satu Nou(Lipanesti)',
    'Schiau (Urlati)': 'Schiau(Urlati)',
    'Schiau (Valea Calugareasca)': 'Schiau(Valea Calugareasca)',
    'Ungureni (Filipestii de Targ)': 'Ungureni(Filipestii de Targ)',
    'Ungureni (Gherghita)': 'Ungureni(Gherghita)',
    'Ungureni (Vadu Sapat)': 'Ungureni(Vadu Sapat)',
  },
  SJ: {
    Dabaceni: 'Dabiceni',
    Stana: 'Stana(Almasu)',
    'Stana (Zalau)': 'Stana(Zalau)',
  },
  SM: {},
  SB: {
    'Veseud (Chirpar)': 'Veseud(Chirpar)',
    'Veseud (Slimnic)': 'Veseud(Slimnic)',
  },
  SV: {
    'Brodina (Izvoarele Sucevei)': 'Brodina(Izvoarele Sucevei)',
    'Brosteni (Draguseni)': 'Brosteni(Draguseni)',
    'Buda (Rasca)': 'Buda(Rasca)',
    'Buda (Zvoristea)': 'Buda(Zvoristea)',
    'Calinesti (Darmanesti)': 'Calinesti(Darmanesti)',
    'Calinesti (Serbauti)': 'Calinesti(serbauti)',
    'Dumbrava (Cornu Luncii)': 'Dumbrava(Cornu Luncii)',
    'Dumbrava (Granicesti)': 'Dumbrava(Granicesti)',
    'Dumbraveni (Rasca)': 'Dumbraveni(Rasca)',
    'Frasin (Brosteni)': 'Frasin(Brosteni)',
    'Liteni (Moara)': 'Liteni(Moara)',
    'Lunca (Milisauti)': 'Lunca(Milisauti)',
    'Lunca (Zamostea)': 'Lunca(Zamostea)',
    'Manastioara (Siret)': 'Manastioara(Siret)',
    'Manastioara (Udesti)': 'Manastioara(Udesti)',
    'Poiana (Dolhasca)': 'Poiana(Dolhasca)',
    'Poiana (Zvoristea)': 'Poiana(Zvoristea)',
    Rasca() {
      throw 'Unavailable destination'
    },
    'Romanesti (Cosna)': 'Romanesti(Cosna)',
    'Romanesti (Granicesti)': 'Romanesti(Granicesti)',
    'Satu Mare (Crucea)': 'Satu Mare(Crucea)',
    'Slatioara (Rasca)': 'Slatioara(Rasca)',
    'Slatioara (Stulpicani)': 'Slatioara(Stulpicani)',
    'Slobozia (Fantanele)': 'Slobozia Sucevei',
    'Slobozia (Zvoristea)': 'Slobozia(Fantanele)',
    'Slobozia Sucevei': 'Slobozia(Zvoristea)',
    'Tesna (Cosna)': 'Tesna(Cosna)',
    'Tesna (Poiana Stampei)': 'Tesna(Poiana Stampei)',
  },
  TR: {
    'Bujoru (Calmatuiu)': 'Bujoru(Calmatuiu)',
    'Ciuperceni (Cosmesti)': 'Ciuperceni(Cosmesti)',
    'Merisani (Babaita)': 'Merisani(Babaita)',
    'Merisani (Dobrotesti)': 'Merisani(Dobrotesti)',
    'Mosteni (Furculesti)': 'Mosteni(Furculesti)',
    'Purani (Vitanesti)': 'Purani(Vitanesti)',
    'Silistea (Vitanesti)': 'Silistea(Vitanesti)',
    'Stejaru (Crangeni)': 'Stejaru(Crangeni)',
  },
  TM: {
    'Bucovat (Dumbrava)': 'Bucovat(Dumbrava)',
    'Bucovat (Remetea Mare)': 'Bucovat(Remetea Mare)',
    Florica() {
      throw 'Unavailable destination'
    },
    'Hodos (Brestovat)': 'Hodos(Brestovat)',
    'Hodos (Darova)': 'Hodos(Darova)',
    'Padureni (Victor Vlad Delamarina)': 'Padureni(Victor Vlad Delamarina)',
  },
  TL: {},
  VL: {
    'Barsesti (Budesti)': 'Barsesti(Budesti)',
    'Barsesti (Mihaesti)': 'Barsesti(Mihaesti)',
    'Berbesti (Lalosu)': 'Berbesti(Lalosu)',
    'Bodesti (Alunu)': 'Bodesti(Alunu)',
    'Bodesti (Barbatesti)': 'Bodesti(Barbatesti)',
    'Bogdanesti (Bujoreni)': 'Bogdanesti(Bujoreni)',
    'Bogdanesti (Otesani)': 'Bogdanesti(Otesani)',
    'Bogdanesti (Tomsani)': 'Bogdanesti(Tomsani)',
    'Budesti (Diculesti)': 'Budesti(Diculesti)',
    'Cazanesti (Ghioroiu)': 'Cazanesti(Ghioroiu)',
    'Cazanesti (Milcoiu)': 'Cazanesti(Milcoiu)',
    'Cazanesti (Ramnicu Valcea)': 'Cazanesti(Ramnicu Valcea)',
    'Cermegesti (Ladesti)': 'Cermegesti(Ladesti)',
    'Cermegesti (Pesceana)': 'Cermegesti(Pesceana)',
    'Coasta (Golesti)': 'Coasta(Golesti)',
    'Coasta (Pausesti-Maglasi)': 'Coasta(Pausesti-Maglasi)',
    'Copaceni (Racovita)': 'Copaceni(Racovita)',
    'Daesti (Popesti)': 'Daesti(Popesti)',
    'Dealu Mare (Galicea)': 'Dealu Mare(Galicea)',
    'Dealu Mare (Gusoeni)': 'Dealu Mare(Gusoeni)',
    'Dealu Mare (Ionesti)': 'Dealu Mare(Ionesti)',
    'Delureni (Ionesti)': 'Delureni(Ionesti)',
    'Delureni (Stoilesti)': 'Delureni(Stoilesti)',
    'Delureni (Valea Mare)': 'Delureni(Valea Mare)',
    'Draganesti (Brezoi)': 'Draganesti(Brezoi)',
    'Draganesti (Golesti)': 'Draganesti(Golesti)',
    'Fauresti (Zatreni)': 'Fauresti(Zatreni)',
    Feteni() {
      throw 'Unavailable destination'
    },
    'Geamana (Dragoesti)': 'Geamana(Dragoesti)',
    'Geamana (Stoilesti)': 'Geamana(Stoilesti)',
    Goranu() {
      throw 'Unavailable destination'
    },
    'Gorunesti (Balcesti)': 'Gorunesti(Balcesti)',
    'Gorunesti (Slatioara)': 'Gorunesti(Slatioara)',
    'Izvoru Rece (Stoilesti)': 'Izvoru Rece(Stoilesti)',
    'Izvoru Rece (Vaideeni)': 'Izvoru Rece(Vaideeni)',
    'Linia (Budesti)': 'Linia(Budesti)',
    'Linia (Gradistea)': 'Linia(Gradistea)',
    'Lunca (Bujoreni)': 'Lunca(Bujoreni)',
    'Lunca (Ocnele Mari)': 'Lunca(Ocnele Mari)',
    'Madulari (Cernisoara)': 'Madulari(Cernisoara)',
    'Maldaresti (Ladesti)': 'Maldaresti(Ladesti)',
    'Maldaresti (Maciuca)': 'Maldaresti(Maciuca)',
    'Olteanca (Glavile)': 'Olteanca(Glavile)',
    'Olteanca (Ladesti)': 'Olteanca(Ladesti)',
    'Pietrari (Pausesti-Maglasi)': 'Pietrari(Pausesti-Maglasi)',
    'Plesoiu (Livezi)': 'Plesoiu(Livezi)',
    'Plesoiu (Nicolae Balcescu)': 'Plesoiu(Nicolae Balcescu)',
    'Popesti (Fartatesti)': 'Popesti(Fartatesti)',
    'Popesti (Golesti)': 'Popesti(Golesti)',
    'Popesti (Ladesti)': 'Popesti(Ladesti)',
    'Popesti (Maciuca)': 'Popesti(Maciuca)',
    'Popesti (Nicolae Balcescu)': 'Popesti(Nicolae Balcescu)',
    'Popesti (Sinesti)': 'Popesti(Sinesti)',
    'Popesti (Stoenesti)': 'Popesti(Stoenesti)',
    'Popesti (Tetoiu)': 'Popesti(Tetoiu)',
    'Racovita (Budesti)': 'Racovita(Budesti)',
    'Ramesti (Horezu)': 'Ramesti(Horezu)',
    'Ramesti (Susani)': 'Ramesti(susani)',
    'Roesti (Pesceana)': 'Roesti(Pesceana)',
    'Rugetu (Mihaesti)': 'Rugetu(Mihaesti)',
    'Rugetu (Slatioara)': 'Rugetu(Slatioara)',
    'Seaca (Calimanesti)': 'Seaca(Calimanesti)',
    'Seaca (Salatrucel)': 'Seaca(Salatrucel)',
    'Serbanesti (Lapusata)': 'serbanesti(Lapusata)',
    'Serbanesti (Pausesti)': 'serbanesti(Pausesti)',
    'Serbanesti (Salatrucel)': 'serbanesti(Salatrucel)',
    'Serbanesti (Stefanesti)': 'serbanesti(stefanesti)',
    'Stanesti (Stoilesti)': 'Stanesti(Stoilesti)',
    'Stefanesti (Maciuca)': 'stefanesti(Maciuca)',
    'Stoenesti (Berislavesti)': 'Stoenesti(Berislavesti)',
    'Ursi (Popesti)': 'Ursi(Popesti)',
    'Ursi (Stoilesti)': 'Ursi(Stoilesti)',
    'Valea Caselor (Dragasani)': 'Valea Caselor(Dragasani)',
    'Valea Caselor (Popesti)': 'Valea Caselor(Popesti)',
    'Valea Mare (Babeni)': 'Valea Mare(Babeni)',
    'Valea Mare (Berbesti)': 'Valea Mare(Berbesti)',
    'Valeni (Pausesti)': 'Valeni(Pausesti)',
    'Valeni (Zatreni)': 'Valeni(Zatreni)',
  },
  VS: {
    Albesti: 'Albesti(Delesti)',
    'Albesti (Delesti)': 'Albesti',
    'Armaseni (Bacesti)': 'Armaseni(Bacesti)',
    'Armaseni (Bunesti-Averesti)': 'Armaseni(Bunesti-Averesti)',
    Bogdanesti: 'Bogdanesti(Falciu)',
    'Bogdanesti (Falciu)': 'Bogdanesti',
    'Buda (Alexandru Vlahuta)': 'Buda(Alexandru Vlahuta)',
    'Buda (Bogdanesti)': 'Buda(Bogdanesti)',
    'Buda (Osesti)': 'Buda(Osesti)',
    Coroiesti: 'Coroiesti(Bogdanita)',
    'Coroiesti (Bogdanita)': 'Coroiesti',
    Deleni: 'Deleni(Hoceni)',
    'Deleni (Hoceni)': 'Deleni',
    Draxeni() {
      throw 'Unavailable destination'
    },
    'Epureni (Duda-Epureni)': 'Epureni(Duda-Epureni)',
    'Fundatura (Arsura)': 'Fundatura Mare',
    'Fundatura (Delesti)': 'Fundatura Mica',
    'Fundatura Mare': 'Fundatura(Arsura)',
    'Fundatura Mica': 'Fundatura(Delesti)',
    'Fundu Vaii (Lipovat)': 'Fundu Vaii(Lipovat)',
    'Fundu Vaii (Poienesti)': 'Fundu Vaii(Poienesti)',
    'Ghermanesti (Banca)': 'Ghermanesti(Banca)',
    'Ghermanesti (Dranceni)': 'Ghermanesti(Dranceni)',
    'Ivanesti (Padureni)': 'Ivanesti(Padureni)',
    'Leosti (Padureni)': 'Leosti(Padureni)',
    'Leosti (Tatarani)': 'Leosti(Tatarani)',
    'Macresti (Rebricea)': 'Macresti(Rebricea)',
    'Macresti (Zapodeni)': 'Macresti(Zapodeni)',
    'Manastirea (Delesti)': 'Manastirea(Delesti)',
    'Manastirea (Malusteni)': 'Manastirea(Malusteni)',
    'Miclesti (Banca)': 'Miclesti(Banca)',
    'Obarseni (Vinderei)': 'Obarseni(Vinderei)',
    'Obarseni (Voinesti)': 'Obarseni(Voinesti)',
    'Padureni (Osesti)': 'Padureni(Osesti)',
    'Popeni (Gagesti)': 'Popeni(Gagesti)',
    'Popeni (Zorleni)': 'Popeni(Zorleni)',
    'Popesti (Dragomiresti)': 'Popesti(Dragomiresti)',
    'Popesti (Miclesti)': 'Popesti(Miclesti)',
    'Rascani (Danesti)': 'Rascani(Danesti)',
    'Rascani (Suletea)': 'Rascani(suletea)',
    'Rediu (Hoceni)': 'Rediu(Hoceni)',
    'Rediu (Rosiesti)': 'Rediu(Rosiesti)',
    'Rediu (Vaslui)': 'Rediu(Vaslui)',
    'Satu Nou (Banca)': 'Satu Nou(Banca)',
    'Satu Nou (Berezeni)': 'Satu Nou(Berezeni)',
    'Satu Nou (Cretesti)': 'Satu Nou(Cretesti)',
    'Satu Nou (Muntenii de Sus)': 'Satu Nou(Muntenii de Sus)',
    'Satu Nou (Pochidia)': 'Satu Nou(Pochidia)',
    'Satu Nou (Solesti)': 'Satu Nou(Solesti)',
    'Silistea (Iana)': 'Silistea(Iana)',
    'Silistea (Pungesti)': 'Silistea(Pungesti)',
    'Silistea (Todiresti)': 'Silistea(Todiresti)',
    'Tatarani (Danesti)': 'Tatarani(Danesti)',
    'Valea Mare (Dumesti)': 'Valea Mare(Dumesti)',
    'Valea Mare (Ivanesti)': 'Valea Mare(Ivanesti)',
    'Valea Mare (Negresti)': 'Valea Mare(Negresti)',
    'Valeni (Padureni)': 'Valeni(Padureni)',
    'Valeni (Viisoara)': 'Valeni(Viisoara)',
    'Viisoara (Todiresti)': 'Viisoara(Todiresti)',
    'Viisoara (Vaslui)': 'Viisoara(Vaslui)',
    'Voinesti (Vulturesti)': 'Voinesti(Vulturesti)',
  },
  VN: {
    'Blidari (Carligele)': 'Blidari(Carligele)',
    'Blidari (Dumitresti)': 'Blidari(Dumitresti)',
    'Costisa (Homocea)': 'Costisa de Sus',
    'Costisa (Tanasoaia)': 'Costisa(Homocea)',
    'Costisa de Sus': 'Costisa(Tanasoaia)',
    'Dragosloveni (Dumbraveni)': 'Dragosloveni(Dumbraveni)',
    'Dragosloveni (Soveja)': 'Dragosloveni(Soveja)',
    'Dumbrava (Panciu)': 'Dumbrava(Panciu)',
    'Dumbrava (Poiana Cristei)': 'Dumbrava(Poiana Cristei)',
    Jitia: 'Jitia de Jos',
    'Jitia de Jos': 'Jitia',
    'Nanesti (Tanasoaia)': 'Nanesti(Tanasoaia)',
    Nereju: 'Nereju Mic',
    'Nereju Mic': 'Nereju',
    'Padureni (Jaristea)': 'Padureni(Jaristea)',
    'Padureni (Marasesti)': 'Padureni(Marasesti)',
    'Padureni (Tamboesti)': 'Padureni(Tamboesti)',
    'Pietroasa (Bolotesti)': 'Pietroasa(Bolotesti)',
    'Pietroasa (Campineanca)': 'Pietroasa(Campineanca)',
    'Pietroasa (Tamboesti)': 'Pietroasa(Tamboesti)',
    'Pietroasa (Vartescoiu)': 'Pietroasa(Vartescoiu)',
    Poiana: 'Poiana Cristei',
    'Poiana Cristei': 'Poiana Stoichii',
    'Poiana Stoichii': 'Poiana',
    'Satu Nou (Ciorasti)': 'Satu Nou(Ciorasti)',
    'Satu Nou (Panciu)': 'Satu Nou(Panciu)',
    'Valeni (Movilita)': 'Valeni(Movilita)',
    'Valeni (Ruginesti)': 'Valeni(Ruginesti)',
    'Valeni (Straoane)': 'Valeni(Straoane)',
    'Viisoara (Paunesti)': 'Viisoara(Paunesti)',
    'Viisoara (Vidra)': 'Viisoara(Vidra)',
  },
}
